/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCareersRouteImport } from './routes/_authenticated/admin.careers'
import { Route as AuthenticatedAdminCatalogRouteImport } from './routes/_authenticated/admin.catalog'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedLearnTopicSlugRouteImport } from './routes/_authenticated/learn.$topicSlug'
import { Route as AuthenticatedPremiumIndexRouteImport } from './routes/_authenticated/premium.index'
import { Route as AuthenticatedPremiumCareerRecommendationsRouteImport } from './routes/_authenticated/premium.career-recommendations'
import { Route as AuthenticatedPremiumCareerSwitchRouteImport } from './routes/_authenticated/premium.career-switch'
import { Route as AuthenticatedPremiumInterviewPrepRouteImport } from './routes/_authenticated/premium.interview-prep'
import { Route as AuthenticatedPremiumInterviewQuestionsRouteImport } from './routes/_authenticated/premium.interview-questions'
import { Route as AuthenticatedPremiumMockInterviewRouteImport } from './routes/_authenticated/premium.mock-interview'
import { Route as AuthenticatedPremiumResumeAnalysisRouteImport } from './routes/_authenticated/premium.resume-analysis'
import { Route as AuthenticatedPremiumResumeOptimizationRouteImport } from './routes/_authenticated/premium.resume-optimization'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCareersRoute =
  AuthenticatedAdminCareersRouteImport.update({
    id: '/admin/careers',
    path: '/admin/careers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogRoute =
  AuthenticatedAdminCatalogRouteImport.update({
    id: '/admin/catalog',
    path: '/admin/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/admin/contact',
    path: '/admin/contact',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AuthenticatedJobsRoute,
} as any)
const AuthenticatedLearnTopicSlugRoute =
  AuthenticatedLearnTopicSlugRouteImport.update({
    id: '/learn/$topicSlug',
    path: '/learn/$topicSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPremiumIndexRoute =
  AuthenticatedPremiumIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumCareerRecommendationsRoute =
  AuthenticatedPremiumCareerRecommendationsRouteImport.update({
    id: '/career-recommendations',
    path: '/career-recommendations',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumCareerSwitchRoute =
  AuthenticatedPremiumCareerSwitchRouteImport.update({
    id: '/career-switch',
    path: '/career-switch',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumInterviewPrepRoute =
  AuthenticatedPremiumInterviewPrepRouteImport.update({
    id: '/interview-prep',
    path: '/interview-prep',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumInterviewQuestionsRoute =
  AuthenticatedPremiumInterviewQuestionsRouteImport.update({
    id: '/interview-questions',
    path: '/interview-questions',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumMockInterviewRoute =
  AuthenticatedPremiumMockInterviewRouteImport.update({
    id: '/mock-interview',
    path: '/mock-interview',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumResumeAnalysisRoute =
  AuthenticatedPremiumResumeAnalysisRouteImport.update({
    id: '/resume-analysis',
    path: '/resume-analysis',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedPremiumResumeOptimizationRoute =
  AuthenticatedPremiumResumeOptimizationRouteImport.update({
    id: '/resume-optimization',
    path: '/resume-optimization',
    getParentRoute: () => AuthenticatedPremiumRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/progress': typeof AuthenticatedProgressRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/learn/$topicSlug': typeof AuthenticatedLearnTopicSlugRoute
  '/premium/career-recommendations': typeof AuthenticatedPremiumCareerRecommendationsRoute
  '/premium/career-switch': typeof AuthenticatedPremiumCareerSwitchRoute
  '/premium/interview-prep': typeof AuthenticatedPremiumInterviewPrepRoute
  '/premium/interview-questions': typeof AuthenticatedPremiumInterviewQuestionsRoute
  '/premium/mock-interview': typeof AuthenticatedPremiumMockInterviewRoute
  '/premium/resume-analysis': typeof AuthenticatedPremiumResumeAnalysisRoute
  '/premium/resume-optimization': typeof AuthenticatedPremiumResumeOptimizationRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/premium/': typeof AuthenticatedPremiumIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers': typeof CareersIndexRoute
  '/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/learn/$topicSlug': typeof AuthenticatedLearnTopicSlugRoute
  '/premium/career-recommendations': typeof AuthenticatedPremiumCareerRecommendationsRoute
  '/premium/career-switch': typeof AuthenticatedPremiumCareerSwitchRoute
  '/premium/interview-prep': typeof AuthenticatedPremiumInterviewPrepRoute
  '/premium/interview-questions': typeof AuthenticatedPremiumInterviewQuestionsRoute
  '/premium/mock-interview': typeof AuthenticatedPremiumMockInterviewRoute
  '/premium/resume-analysis': typeof AuthenticatedPremiumResumeAnalysisRoute
  '/premium/resume-optimization': typeof AuthenticatedPremiumResumeOptimizationRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/premium': typeof AuthenticatedPremiumIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRouteWithChildren
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/careers/': typeof CareersIndexRoute
  '/_authenticated/admin/careers': typeof AuthenticatedAdminCareersRoute
  '/_authenticated/admin/catalog': typeof AuthenticatedAdminCatalogRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/learn/$topicSlug': typeof AuthenticatedLearnTopicSlugRoute
  '/_authenticated/premium/career-recommendations': typeof AuthenticatedPremiumCareerRecommendationsRoute
  '/_authenticated/premium/career-switch': typeof AuthenticatedPremiumCareerSwitchRoute
  '/_authenticated/premium/interview-prep': typeof AuthenticatedPremiumInterviewPrepRoute
  '/_authenticated/premium/interview-questions': typeof AuthenticatedPremiumInterviewQuestionsRoute
  '/_authenticated/premium/mock-interview': typeof AuthenticatedPremiumMockInterviewRoute
  '/_authenticated/premium/resume-analysis': typeof AuthenticatedPremiumResumeAnalysisRoute
  '/_authenticated/premium/resume-optimization': typeof AuthenticatedPremiumResumeOptimizationRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/premium/': typeof AuthenticatedPremiumIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/assessments'
    | '/dashboard'
    | '/jobs'
    | '/onboarding'
    | '/premium'
    | '/progress'
    | '/projects'
    | '/roadmap'
    | '/settings'
    | '/skills'
    | '/careers/$slug'
    | '/careers/'
    | '/admin/careers'
    | '/admin/catalog'
    | '/admin/contact'
    | '/admin/jobs'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/learn/$topicSlug'
    | '/premium/career-recommendations'
    | '/premium/career-switch'
    | '/premium/interview-prep'
    | '/premium/interview-questions'
    | '/premium/mock-interview'
    | '/premium/resume-analysis'
    | '/premium/resume-optimization'
    | '/projects/$projectId'
    | '/admin/'
    | '/jobs/'
    | '/premium/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/assessments'
    | '/dashboard'
    | '/onboarding'
    | '/progress'
    | '/roadmap'
    | '/settings'
    | '/skills'
    | '/careers/$slug'
    | '/careers'
    | '/admin/careers'
    | '/admin/catalog'
    | '/admin/contact'
    | '/admin/jobs'
    | '/admin/users'
    | '/jobs/$jobId'
    | '/learn/$topicSlug'
    | '/premium/career-recommendations'
    | '/premium/career-switch'
    | '/premium/interview-prep'
    | '/premium/interview-questions'
    | '/premium/mock-interview'
    | '/premium/resume-analysis'
    | '/premium/resume-optimization'
    | '/projects/$projectId'
    | '/admin'
    | '/jobs'
    | '/premium'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/assessments'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/progress'
    | '/_authenticated/projects'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/skills'
    | '/careers/$slug'
    | '/careers/'
    | '/_authenticated/admin/careers'
    | '/_authenticated/admin/catalog'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/users'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/learn/$topicSlug'
    | '/_authenticated/premium/career-recommendations'
    | '/_authenticated/premium/career-switch'
    | '/_authenticated/premium/interview-prep'
    | '/_authenticated/premium/interview-questions'
    | '/_authenticated/premium/mock-interview'
    | '/_authenticated/premium/resume-analysis'
    | '/_authenticated/premium/resume-optimization'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/admin/'
    | '/_authenticated/jobs/'
    | '/_authenticated/premium/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/careers': {
      id: '/_authenticated/admin/careers'
      path: '/admin/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AuthenticatedAdminCareersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalog': {
      id: '/_authenticated/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedJobsRoute
    }
    '/_authenticated/learn/$topicSlug': {
      id: '/_authenticated/learn/$topicSlug'
      path: '/learn/$topicSlug'
      fullPath: '/learn/$topicSlug'
      preLoaderRoute: typeof AuthenticatedLearnTopicSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium/': {
      id: '/_authenticated/premium/'
      path: '/'
      fullPath: '/premium/'
      preLoaderRoute: typeof AuthenticatedPremiumIndexRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/career-recommendations': {
      id: '/_authenticated/premium/career-recommendations'
      path: '/career-recommendations'
      fullPath: '/premium/career-recommendations'
      preLoaderRoute: typeof AuthenticatedPremiumCareerRecommendationsRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/career-switch': {
      id: '/_authenticated/premium/career-switch'
      path: '/career-switch'
      fullPath: '/premium/career-switch'
      preLoaderRoute: typeof AuthenticatedPremiumCareerSwitchRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/interview-prep': {
      id: '/_authenticated/premium/interview-prep'
      path: '/interview-prep'
      fullPath: '/premium/interview-prep'
      preLoaderRoute: typeof AuthenticatedPremiumInterviewPrepRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/interview-questions': {
      id: '/_authenticated/premium/interview-questions'
      path: '/interview-questions'
      fullPath: '/premium/interview-questions'
      preLoaderRoute: typeof AuthenticatedPremiumInterviewQuestionsRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/mock-interview': {
      id: '/_authenticated/premium/mock-interview'
      path: '/mock-interview'
      fullPath: '/premium/mock-interview'
      preLoaderRoute: typeof AuthenticatedPremiumMockInterviewRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/resume-analysis': {
      id: '/_authenticated/premium/resume-analysis'
      path: '/resume-analysis'
      fullPath: '/premium/resume-analysis'
      preLoaderRoute: typeof AuthenticatedPremiumResumeAnalysisRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/premium/resume-optimization': {
      id: '/_authenticated/premium/resume-optimization'
      path: '/resume-optimization'
      fullPath: '/premium/resume-optimization'
      preLoaderRoute: typeof AuthenticatedPremiumResumeOptimizationRouteImport
      parentRoute: typeof AuthenticatedPremiumRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
  }
}

interface AuthenticatedJobsRouteChildren {
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
}

const AuthenticatedJobsRouteChildren: AuthenticatedJobsRouteChildren = {
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
}

const AuthenticatedJobsRouteWithChildren =
  AuthenticatedJobsRoute._addFileChildren(AuthenticatedJobsRouteChildren)

interface AuthenticatedPremiumRouteChildren {
  AuthenticatedPremiumCareerRecommendationsRoute: typeof AuthenticatedPremiumCareerRecommendationsRoute
  AuthenticatedPremiumCareerSwitchRoute: typeof AuthenticatedPremiumCareerSwitchRoute
  AuthenticatedPremiumInterviewPrepRoute: typeof AuthenticatedPremiumInterviewPrepRoute
  AuthenticatedPremiumInterviewQuestionsRoute: typeof AuthenticatedPremiumInterviewQuestionsRoute
  AuthenticatedPremiumMockInterviewRoute: typeof AuthenticatedPremiumMockInterviewRoute
  AuthenticatedPremiumResumeAnalysisRoute: typeof AuthenticatedPremiumResumeAnalysisRoute
  AuthenticatedPremiumResumeOptimizationRoute: typeof AuthenticatedPremiumResumeOptimizationRoute
  AuthenticatedPremiumIndexRoute: typeof AuthenticatedPremiumIndexRoute
}

const AuthenticatedPremiumRouteChildren: AuthenticatedPremiumRouteChildren = {
  AuthenticatedPremiumCareerRecommendationsRoute:
    AuthenticatedPremiumCareerRecommendationsRoute,
  AuthenticatedPremiumCareerSwitchRoute: AuthenticatedPremiumCareerSwitchRoute,
  AuthenticatedPremiumInterviewPrepRoute:
    AuthenticatedPremiumInterviewPrepRoute,
  AuthenticatedPremiumInterviewQuestionsRoute:
    AuthenticatedPremiumInterviewQuestionsRoute,
  AuthenticatedPremiumMockInterviewRoute:
    AuthenticatedPremiumMockInterviewRoute,
  AuthenticatedPremiumResumeAnalysisRoute:
    AuthenticatedPremiumResumeAnalysisRoute,
  AuthenticatedPremiumResumeOptimizationRoute:
    AuthenticatedPremiumResumeOptimizationRoute,
  AuthenticatedPremiumIndexRoute: AuthenticatedPremiumIndexRoute,
}

const AuthenticatedPremiumRouteWithChildren =
  AuthenticatedPremiumRoute._addFileChildren(AuthenticatedPremiumRouteChildren)

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRouteWithChildren
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedAdminCareersRoute: typeof AuthenticatedAdminCareersRoute
  AuthenticatedAdminCatalogRoute: typeof AuthenticatedAdminCatalogRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedLearnTopicSlugRoute: typeof AuthenticatedLearnTopicSlugRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRouteWithChildren,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedAdminCareersRoute: AuthenticatedAdminCareersRoute,
  AuthenticatedAdminCatalogRoute: AuthenticatedAdminCatalogRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedLearnTopicSlugRoute: AuthenticatedLearnTopicSlugRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CareersRouteChildren {
  CareersSlugRoute: typeof CareersSlugRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSlugRoute: CareersSlugRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
