-- CONTENT EXPANSION -- Phase E (assessments), new-skills batch 2
--
-- Completes assessment coverage for all 29 skills added in 20260906010000.
-- Batch 1 (20260906080000) covered 11 skills; this covers the remaining 18:
-- MLOps, LLMs, Cloud (Azure), Cloud (GCP), Monitoring & Observability,
-- Infrastructure as Code, Airflow, NLP, Computer Vision, Generative AI,
-- Cloud Security, Identity & Access Management, Design Patterns, Clean
-- Code, Requirements Analysis, Mobile Development, Database
-- Administration, and Apache Spark. 10 questions each, 180 total.

INSERT INTO public.assessments (slug, title, skill_id, difficulty, description)
SELECT v.slug, v.title, s.id, v.diff::public.difficulty_level, v.descr
FROM (VALUES
  ('mlops-fundamentals-quiz','MLOps Fundamentals','mlops','advanced','Reproducibility, feature stores, drift, and CI/CD for machine learning.'),
  ('llm-fundamentals-quiz','Large Language Model Fundamentals','llms','intermediate','Tokens, context windows, hallucination, and model behavior.'),
  ('cloud-azure-fundamentals-quiz','Cloud (Azure) Fundamentals','cloud-azure','intermediate','Resource groups, compute options, storage, and identity.'),
  ('cloud-gcp-fundamentals-quiz','Cloud (GCP) Fundamentals','cloud-gcp','intermediate','Projects, compute options, storage classes, and IAM.'),
  ('monitoring-observability-quiz','Monitoring & Observability','monitoring-observability','intermediate','Metrics, logs, traces, SLOs, and alert design.'),
  ('infrastructure-as-code-quiz','Infrastructure as Code','infrastructure-as-code','intermediate','Idempotency, declarative vs imperative, drift, and review.'),
  ('airflow-fundamentals-quiz','Apache Airflow Fundamentals','airflow','advanced','DAGs, operators, scheduling, retries, and idempotent tasks.'),
  ('nlp-fundamentals-quiz','Natural Language Processing Fundamentals','nlp','intermediate','Tokenization, embeddings, NER, and context.'),
  ('computer-vision-quiz','Computer Vision Fundamentals','computer-vision','advanced','Convolution, classification vs detection vs segmentation, and transfer learning.'),
  ('generative-ai-quiz','Generative AI Fundamentals','generative-ai','intermediate','Generative vs discriminative models, diffusion, and responsible use.'),
  ('cloud-security-quiz','Cloud Security Fundamentals','cloud-security','advanced','Shared responsibility, misconfigurations, CSPM, and encryption.'),
  ('identity-access-management-quiz','Identity & Access Management','identity-access-management','intermediate','RBAC, least privilege, MFA, and service accounts.'),
  ('design-patterns-quiz','Design Patterns Fundamentals','design-patterns','intermediate','Singleton, Factory, Observer, and Strategy.'),
  ('clean-code-quiz','Clean Code Fundamentals','clean-code','beginner','Naming, function size, comments, and code smells.'),
  ('requirements-analysis-quiz','Requirements Analysis Fundamentals','requirements-analysis','intermediate','User stories, acceptance criteria, elicitation, and traceability.'),
  ('mobile-development-quiz','Mobile Development Fundamentals','mobile-development','intermediate','Native vs cross-platform, offline-first, lifecycle, and performance.'),
  ('database-administration-quiz','Database Administration Fundamentals','database-administration','advanced','Backups, query plans, replication, and connection pooling.'),
  ('apache-spark-quiz','Apache Spark Fundamentals','apache-spark','advanced','Transformations vs actions, lazy evaluation, partitioning, and DataFrames.')
) AS v(slug, title, skill_slug, diff, descr)
JOIN public.skills s ON s.slug = v.skill_slug
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.assessment_questions (assessment_id, prompt, options, correct_index, explanation, sort_order)
SELECT a.id, v.prompt, v.opts, v.correct, v.expl, v.ord
FROM (VALUES

-- ============ mlops-fundamentals-quiz ============
('mlops-fundamentals-quiz','What is one key difference between a notebook and a production ML system?',ARRAY['A notebook is always faster','A production system needs versioned code and a repeatable training pipeline that a notebook does not naturally provide','Notebooks cannot run Python','There is no difference'],1,'Production ML needs reproducibility and versioning that a one-off notebook typically lacks.',1),
('mlops-fundamentals-quiz','Why is experiment tracking important for reproducibility?',ARRAY['It logs the code style only','It records data version, hyperparameters and metrics so a specific production model can be traced back to what produced it','It makes training faster','It replaces the need for testing'],1,'Tracking lets you answer exactly what produced a given model months later.',2),
('mlops-fundamentals-quiz','What is training/serving skew?',ARRAY['A model that is skewed toward one class','When a feature is computed differently in training vs live serving, causing the model to see different-looking inputs','A GPU hardware issue','Overfitting'],1,'Mismatched feature computation logic between training and serving degrades real-world performance.',3),
('mlops-fundamentals-quiz','What does a feature store help prevent?',ARRAY['Slow training','Training/serving skew, by centralizing feature computation logic','Data loss','Model versioning'],1,'A feature store ensures training and serving compute features the same way.',4),
('mlops-fundamentals-quiz','What is data drift?',ARRAY['The model''s code changing','The input data distribution shifting over time, causing model performance to degrade silently','A bug in training code','A GPU failure'],1,'Data drift is a real-world shift in inputs that a static model was not trained to handle.',5),
('mlops-fundamentals-quiz','What is concept drift?',ARRAY['Data drift renamed','The relationship between inputs and outputs changing over time, even if input distribution looks similar','A training data leak','Hardware drift'],1,'Concept drift means the underlying pattern the model learned no longer holds.',6),
('mlops-fundamentals-quiz','Why can a fraud model trained on pre-pandemic data risk degrading without anyone noticing?',ARRAY['The model crashes immediately','Consumer behavior shifted with no error thrown, only a silent decline in real-world precision that only monitoring would catch','The model auto-retrains','Fraud stopped happening'],1,'Drift degrades performance silently unless actively monitored.',7),
('mlops-fundamentals-quiz','What should an ML CI/CD pipeline typically validate before allowing a new model to deploy?',ARRAY['Nothing, deploy immediately','That the new model beats the currently-deployed model''s accuracy on a fixed validation set','Only that the code compiles','The size of the model file'],1,'A validation gate prevents a regression from silently reaching production.',8),
('mlops-fundamentals-quiz','"We retrained the model and it got worse" is hard to debug without:',ARRAY['More GPUs','Experiment tracking recording exactly what data/hyperparameters produced each model version','A bigger team','Faster internet'],1,'Without tracking, you cannot compare what changed between the good and bad runs.',9),
('mlops-fundamentals-quiz','Why is treating a Jupyter notebook as a deployable artifact a common MLOps mistake?',ARRAY['Notebooks are illegal in production','It typically lacks reproducibility, versioning, and a defined API contract needed for reliable production use','Notebooks are too fast','Notebooks cannot import libraries'],1,'Notebooks are exploratory tools, not production-grade deployable artifacts.',10),

-- ============ llm-fundamentals-quiz ============
('llm-fundamentals-quiz','What is a "token" in the context of LLMs?',ARRAY['A full word always','A piece of text, often a subword, that the model processes as its basic unit','A type of API key','A programming language'],1,'Tokens are the model''s basic processing unit, not necessarily whole words.',1),
('llm-fundamentals-quiz','Why can a 100,000-character document sometimes fail with a "context length exceeded" error even though it seems short?',ARRAY['The document has too many words','Token counts do not map cleanly onto character/word counts, and 100,000 characters can be far more tokens than the limit allows','The API is broken','Documents cannot be sent to LLMs'],1,'Tokenization ratios vary, so character count is a poor proxy for token count.',2),
('llm-fundamentals-quiz','What is a context window?',ARRAY['The browser window running the chat UI','The maximum number of tokens a model can consider at once','A visual UI element','The model''s training dataset size'],1,'The context window bounds how much text the model can attend to per request.',3),
('llm-fundamentals-quiz','Why might a chatbot seem to "forget" something said much earlier in a long conversation?',ARRAY['This is always a bug','Earlier content may have scrolled outside the context window and is no longer visible to the model','The model has amnesia','Chat history is deleted every message'],1,'Content outside the context window simply is not seen by the model.',4),
('llm-fundamentals-quiz','Why do LLMs hallucinate?',ARRAY['They are poorly coded','They generate the statistically most plausible next token, with no built-in mechanism to verify factual truth','They are intentionally lying','Hallucination only happens with small models'],1,'Hallucination follows directly from how next-token prediction works.',5),
('llm-fundamentals-quiz','What is the key difference between a base model and an instruction-tuned model?',ARRAY['There is no difference','An instruction-tuned model is further trained on examples of instructions and desired responses, making it behave like an assistant','Base models are always larger','Instruction-tuned models cannot generate text'],1,'Instruction tuning is what turns a raw text-completion model into a helpful assistant.',6),
('llm-fundamentals-quiz','What would a base model likely do if given "What is the capital of France?"',ARRAY['Always answer correctly','Possibly continue with more geography trivia questions rather than directly answering','Refuse to respond','Answer in French only'],1,'A base model continues plausible text rather than following an instruction.',7),
('llm-fundamentals-quiz','What effect does lowering temperature have on an LLM''s output?',ARRAY['It makes output longer','It makes output more deterministic and focused, reducing randomness','It slows down the API','It increases hallucination'],1,'Lower temperature narrows the range of likely next tokens chosen.',8),
('llm-fundamentals-quiz','For a creative writing task, would you likely want a higher or lower temperature than for a factual lookup task?',ARRAY['Lower, for consistency','Higher, to allow more variety and creativity','Temperature does not matter for creative tasks','Always use 0'],1,'Creative tasks benefit from the variety higher temperature introduces.',9),
('llm-fundamentals-quiz','Why is fluent, confident-sounding LLM output not the same as verified output?',ARRAY['Fluency and accuracy are the same thing','The model can produce plausible-sounding but fabricated content since it has no built-in fact-checking mechanism','LLMs are always accurate','Fluent output is always correct'],1,'Fluency is a property of language generation, not a guarantee of truth.',10),

-- ============ cloud-azure-fundamentals-quiz ============
('cloud-azure-fundamentals-quiz','What is an Azure resource group?',ARRAY['A billing currency','A logical container for resources that typically share a lifecycle and can be deleted together','A type of virtual machine','A security certificate'],1,'Resource groups organize related resources for shared lifecycle management.',1),
('cloud-azure-fundamentals-quiz','Which compute option gives full OS control but requires you to manage patching and scaling yourself?',ARRAY['Azure Functions','Azure VMs','App Service','None of these'],1,'VMs trade managed convenience for full control.',2),
('cloud-azure-fundamentals-quiz','Which compute option is best for a short task triggered by a file upload, with no server to manage?',ARRAY['Azure VMs','Azure Functions','App Service','A dedicated cluster'],1,'Functions are designed for short, event-triggered, serverless work.',3),
('cloud-azure-fundamentals-quiz','Which Azure storage type is best for unstructured files like uploaded photos?',ARRAY['Table storage','Blob storage','Queue storage','File storage only'],1,'Blob storage is designed for unstructured file data.',4),
('cloud-azure-fundamentals-quiz','What is Azure Active Directory / Microsoft Entra ID primarily used for?',ARRAY['Storing files','Identity and access control for users and applications','Running virtual machines','Billing management only'],1,'It is Azure''s identity and access management service.',5),
('cloud-azure-fundamentals-quiz','Why is a managed identity generally safer than embedding a static storage account key in app configuration?',ARRAY['Managed identities are faster','It avoids a long-lived secret that could leak if the configuration is exposed','Keys are illegal in Azure','There is no difference'],1,'Managed identities remove the need for a static, leakable secret.',6),
('cloud-azure-fundamentals-quiz','What is a simple, effective way to reduce cost on a non-production VM only used during business hours?',ARRAY['Delete it permanently','Configure an auto-shutdown schedule outside working hours','Upgrade to a bigger VM','Nothing can be done'],1,'Auto-shutdown avoids paying for idle compute overnight and on weekends.',7),
('cloud-azure-fundamentals-quiz','For a small team needing to run a web API without managing servers, which compute option is typically the best fit?',ARRAY['Azure VMs','App Service','Bare metal servers','None, this is not possible'],1,'App Service is a managed platform requiring no server management.',8),
('cloud-azure-fundamentals-quiz','Why might a company organize resources into separate resource groups per environment (dev/staging/prod)?',ARRAY['It is required by Azure with no benefit','It lets each environment''s resources be managed, billed and deleted independently as a unit','Resource groups are purely cosmetic','Azure requires exactly one resource group per subscription'],1,'Grouping by environment isolates lifecycle and billing per environment.',9),
('cloud-azure-fundamentals-quiz','Which Azure storage type fits a legacy application that needs to mount a network drive?',ARRAY['Blob storage','File shares','Queue storage','Table storage'],1,'File shares provide SMB-mountable network storage.',10),

-- ============ cloud-gcp-fundamentals-quiz ============
('cloud-gcp-fundamentals-quiz','What is the basic unit of billing, quota, and access control in GCP?',ARRAY['A folder','A project','An organization','A zone'],1,'Every GCP resource belongs to a project, the basic unit of billing and access control.',1),
('cloud-gcp-fundamentals-quiz','Which GCP compute option automatically scales a containerized app to zero when idle, without managing servers?',ARRAY['Compute Engine','Cloud Run','A dedicated VM cluster','None of these'],1,'Cloud Run scales containers automatically, including to zero.',2),
('cloud-gcp-fundamentals-quiz','Which GCP compute option is best for a single function triggered by a file upload?',ARRAY['Compute Engine','Cloud Functions','A managed Kubernetes cluster','A load balancer'],1,'Cloud Functions is designed for single, event-triggered functions.',3),
('cloud-gcp-fundamentals-quiz','Which Cloud Storage class is most appropriate for compliance archives rarely accessed after 30 days?',ARRAY['Standard','Coldline or Archive','Only Standard is available','None, files cannot be archived'],1,'Coldline/Archive classes trade retrieval latency for much lower storage cost.',4),
('cloud-gcp-fundamentals-quiz','Why is granting a service account the broad "Owner" role risky when it only needs to deploy one service?',ARRAY['It is not risky at all','It gives the account far more access than needed, increasing damage if compromised','Owner role is required for all deployments','There is no alternative role'],1,'Least privilege limits blast radius; Owner is far broader than needed.',5),
('cloud-gcp-fundamentals-quiz','What is one way to reduce accidental GCP cost from an "orphaned" resource?',ARRAY['Ignore it, it is harmless','Notice and delete resources like unattached persistent disks left over after a VM was deleted','Never delete any GCP resource','Disable billing alerts'],1,'Orphaned resources like unattached disks silently accrue cost until removed.',6),
('cloud-gcp-fundamentals-quiz','Why might a company use separate GCP projects for dev, staging, and production?',ARRAY['GCP requires this by law','It isolates billing, quota, and IAM policies per environment','Multiple projects are always cheaper','There is no reason to separate them'],1,'Separate projects give clean environment isolation.',7),
('cloud-gcp-fundamentals-quiz','What does a committed use discount typically apply to?',ARRAY['One-time spot usage','Predictable, steady-state workloads committed to over a period of time','Free tier usage only','Storage class selection'],1,'Committed use discounts reward predictable, sustained usage commitments.',8),
('cloud-gcp-fundamentals-quiz','What GCP service manages roles and permissions for identities?',ARRAY['Cloud Storage','IAM','Cloud Functions','BigQuery'],1,'IAM is GCP''s identity and access management service.',9),
('cloud-gcp-fundamentals-quiz','A stateless API with unpredictable traffic should scale down to zero cost when idle. Which compute option fits best?',ARRAY['Compute Engine with a fixed VM size','Cloud Run','A permanently running dedicated server','None of these support scaling to zero'],1,'Cloud Run is purpose-built for this exact scaling pattern.',10),

-- ============ monitoring-observability-quiz ============
('monitoring-observability-quiz','What is the key difference between monitoring and observability?',ARRAY['They are identical','Monitoring watches predefined things; observability lets you ask new questions about internal state you did not anticipate','Observability is only for logs','Monitoring is always more expensive'],1,'Observability is the broader capability beyond predefined dashboards.',1),
('monitoring-observability-quiz','Which of the three observability pillars is best for debugging a specific incident with detailed, timestamped events?',ARRAY['Metrics','Logs','Traces','None of these'],1,'Logs provide the granular detail needed to investigate a specific incident.',2),
('monitoring-observability-quiz','Which pillar is best for finding which specific microservice in a request chain caused a slowdown?',ARRAY['Metrics','Logs','Traces','Alerts'],2,'Traces follow a single request across services, pinpointing where time was spent.',3),
('monitoring-observability-quiz','What makes an alert "good," according to best practice?',ARRAY['It fires as often as possible','It is actionable, tied to a user-facing symptom, with a clear next step','It only requires a dashboard, no action','Alerts should never fire'],1,'Actionability and a clear next step are what make an alert worth having.',4),
('monitoring-observability-quiz','What is an SLI?',ARRAY['A service level improvement plan','A measured metric, like percentage of requests under 200ms','A type of alert','A cloud region'],1,'An SLI is the actual measured indicator behind an SLO target.',5),
('monitoring-observability-quiz','What is an error budget?',ARRAY['A monetary budget for cloud spend','The allowed amount of failure under an SLO, which can be spent deliberately on things like a risky deploy','A list of known bugs','A required log format'],1,'The error budget quantifies how much failure is acceptable before violating the SLO.',6),
('monitoring-observability-quiz','Why is spending some of an error budget on a risky but valuable deploy considered a legitimate decision?',ARRAY['It is never acceptable','The SLO already accounts for some allowed failure, so using it deliberately is a normal tradeoff','Error budgets are purely theoretical','This causes automatic rollback'],1,'Error budgets exist precisely to enable calculated risk-taking.',7),
('monitoring-observability-quiz','What is "alert fatigue"?',ARRAY['Alerts that fire too slowly','Responders becoming desensitized to too many low-value alerts, causing them to miss genuinely critical ones','A hardware failure','A type of network latency'],1,'Alert fatigue is the human cost of excessive low-value alerting.',8),
('monitoring-observability-quiz','Why can having too many non-actionable alerts make a system LESS safe?',ARRAY['More alerts always mean more safety','Responders start ignoring notifications, so a real critical alert can be missed in the noise','Alerts use too much CPU','There is no downside to more alerts'],1,'Noise erodes trust in the alerting signal itself.',9),
('monitoring-observability-quiz','A dashboard shows CPU usage but cannot tell you which specific requests caused a spike. What is missing?',ARRAY['Nothing is missing','Observability -- the ability to ask new, unanticipated questions using the underlying data','More CPU','A bigger dashboard'],1,'This is exactly the gap observability, beyond simple monitoring, is meant to fill.',10),

-- ============ infrastructure-as-code-quiz ============
('infrastructure-as-code-quiz','Why do manual ("ClickOps") infrastructure changes cause problems?',ARRAY['They are always slower to perform','They leave no record of what changed or why and cannot easily be reproduced elsewhere','Cloud consoles do not allow manual changes','There is no downside'],1,'Untracked manual changes are hard to reproduce and audit.',1),
('infrastructure-as-code-quiz','What does it mean for an IaC operation to be idempotent?',ARRAY['It can only run once ever','Running it multiple times with no changes produces the same result, a no-op','It always creates new resources','It requires manual approval every time'],1,'Idempotency makes IaC tools safe to re-run repeatedly.',2),
('infrastructure-as-code-quiz','What is the key difference between declarative and imperative IaC approaches?',ARRAY['They are the same','Declarative describes the desired end state and lets the tool figure out how; imperative is an explicit sequence of steps','Imperative is always safer','Declarative requires no configuration at all'],1,'This is the fundamental distinction between the two IaC styles.',3),
('infrastructure-as-code-quiz','What is "drift" in an IaC context?',ARRAY['A network latency issue','When real infrastructure diverges from what is declared in code, usually from a manual change','A billing anomaly','A type of encryption'],1,'Drift is the gap between declared and actual infrastructure state.',4),
('infrastructure-as-code-quiz','How can a team detect drift before it causes confusion?',ARRAY['They cannot, drift is undetectable','Regularly running a plan/diff step without applying, to surface differences early','Waiting for a production outage','Disabling the IaC tool'],1,'A regular plan/diff step is the standard way to catch drift early.',5),
('infrastructure-as-code-quiz','Why is code review valuable for infrastructure changes, just as for application code?',ARRAY['It is not valuable for infrastructure','It can catch dangerous mistakes, like an overly permissive security group, before they are applied','Reviews slow down deployment with no benefit','Infrastructure changes are never risky'],1,'Review catches infrastructure mistakes the same way it catches code bugs.',6),
('infrastructure-as-code-quiz','What advantage does a declarative tool have when actual state does not match expectations?',ARRAY['None, both approaches behave identically','It can compare desired vs actual state and create only what is missing, rather than blindly re-running every step','Declarative tools always fail in this situation','Imperative scripts handle this better'],1,'Declarative reconciliation avoids duplicate or unnecessary work.',7),
('infrastructure-as-code-quiz','Why does idempotency matter for a tool that might be re-run automatically in a CI/CD pipeline?',ARRAY['It does not matter','A non-idempotent tool could create duplicate resources every time the pipeline runs','Idempotency only matters for databases','CI/CD pipelines never re-run IaC tools'],1,'Automated re-runs require idempotency to be safe.',8),
('infrastructure-as-code-quiz','Someone manually resizes a VM outside of the IaC tool. What will happen on the next plan/diff run?',ARRAY['Nothing, manual changes are invisible','It will surface the VM as drifted from the declared configuration','The IaC tool will crash','The VM will be automatically deleted'],1,'Plan compares real state against declared state and will show the drift.',9),
('infrastructure-as-code-quiz','What long-term problem does habitual manual infrastructure editing (bypassing IaC) create?',ARRAY['No problem, it is more efficient','A cumulative gap between declared and actual infrastructure that is hard to reason about and reproduce','Manual editing is always faster and safer','IaC tools prevent manual edits automatically'],1,'Habitual manual edits erode the reliability guarantee IaC is meant to provide.',10),

-- ============ airflow-fundamentals-quiz ============
('airflow-fundamentals-quiz','What does DAG stand for, and why does it matter for pipelines?',ARRAY['Direct Application Gateway, unrelated to pipelines','Directed Acyclic Graph -- it models tasks with explicit dependencies and no cycles, letting a scheduler parallelize independent work','Data Aggregation Group','Digital Automation Gateway'],1,'DAG structure is what enables safe parallelism and clear dependency management.',1),
('airflow-fundamentals-quiz','What is the difference between an operator and a task in Airflow?',ARRAY['They are identical terms','An operator is a template for a type of work; a task is a specific instantiation of an operator within a DAG','A task defines a DAG''s schedule','Operators only run SQL'],1,'Operators are reusable templates; tasks are the concrete instances in a DAG.',2),
('airflow-fundamentals-quiz','What does "backfilling" allow you to do?',ARRAY['Delete old DAG runs','Run a DAG for past scheduled intervals it missed or that predate when the DAG was created','Backup a database','Restart a failed worker node'],1,'Backfilling processes historical intervals as if the DAG had always been running.',3),
('airflow-fundamentals-quiz','Why is backfilling valuable when adding a brand-new pipeline?',ARRAY['It is not valuable','It lets the pipeline catch up and process historical data as if it had been running all along','Backfilling deletes old data','It only works for real-time streams'],1,'New pipelines often need to process a backlog of historical intervals.',4),
('airflow-fundamentals-quiz','Why does Airflow support automatic retries with a delay for failing tasks?',ARRAY['To make pipelines run slower on purpose','To handle transient failures, like a flaky API, without requiring manual intervention','Retries are required by law','Retries replace the need for monitoring'],1,'Retries absorb short, transient failures automatically.',5),
('airflow-fundamentals-quiz','Why could retrying a failing task indefinitely with no limit be a problem?',ARRAY['It is never a problem','It can hide a real bug instead of just handling a transient failure','Airflow does not support unlimited retries','Unlimited retries always fix the underlying issue'],1,'Unlimited retries can mask a genuine code or data bug.',6),
('airflow-fundamentals-quiz','Why should a data-loading task overwrite a partition rather than append rows on every run?',ARRAY['Appending is always safer','Appending on every run risks creating duplicate data if the task is retried after a partial failure','Overwriting is slower','There is no difference'],1,'Overwrite-based loads are idempotent; append-based loads are not.',7),
('airflow-fundamentals-quiz','What benefit does modeling a pipeline as a DAG provide that a single monolithic script typically does not?',ARRAY['Faster code execution always','The ability for a scheduler to run independent tasks in parallel based on explicit dependencies','DAGs use less memory','DAGs eliminate the need for testing'],1,'Explicit dependency graphs enable safe, correct parallelism.',8),
('airflow-fundamentals-quiz','Which Airflow operator would you use to run an arbitrary Python function as a task?',ARRAY['PostgresOperator','PythonOperator','BashOperator only','There is no such operator'],1,'PythonOperator is designed exactly for this purpose.',9),
('airflow-fundamentals-quiz','What is a key property tasks should have to make retries and backfills safe rather than dangerous?',ARRAY['They should run as fast as possible','Idempotency -- producing the same correct result no matter how many times they are re-run','They should never fail','They should always run in isolation with no dependencies'],1,'Idempotent tasks are what make retries and reruns safe.',10),

-- ============ nlp-fundamentals-quiz ============
('nlp-fundamentals-quiz','Why must text be tokenized before an NLP model can process it?',ARRAY['Tokenization makes text prettier','Models operate on numeric data, not raw strings, so text must be converted into numeric tokens first','Tokenization is optional','Only English text needs tokenization'],1,'Models require numeric input, so tokenization is a necessary preprocessing step.',1),
('nlp-fundamentals-quiz','Why does subword tokenization handle rare/unseen words better than whole-word tokenization?',ARRAY['It does not, whole-word is always better','It can represent a rare word as smaller known pieces even if the full word never appeared in training','Subword tokenization ignores rare words entirely','Rare words are always deleted'],1,'Subword pieces let the model handle novel words by composing known fragments.',2),
('nlp-fundamentals-quiz','What does bag-of-words / TF-IDF fundamentally ignore?',ARRAY['Word frequency','Word order and surrounding context','Vocabulary size','Document length'],1,'These approaches represent documents as unordered word counts/weights.',3),
('nlp-fundamentals-quiz','What do word embeddings capture that bag-of-words does not?',ARRAY['Exact word counts only','Semantic similarity between words, based on patterns of co-occurrence in text','File size','Grammar rules explicitly'],1,'Embeddings encode meaning-based relationships between words.',4),
('nlp-fundamentals-quiz','What is Named Entity Recognition (NER) used for?',ARRAY['Translating text','Identifying and classifying spans of text into categories like person, organization, location, or date','Summarizing documents','Compressing text'],1,'NER extracts structured entity mentions from unstructured text.',5),
('nlp-fundamentals-quiz','Why do older, fixed word embeddings struggle with a word like "bank" that has multiple meanings?',ARRAY['They do not struggle, this is not an issue','They assign one fixed vector per word regardless of context, so different meanings get the same representation','Fixed embeddings only work with nouns','"Bank" is not a real ambiguous word'],1,'Fixed embeddings cannot distinguish a word''s different senses.',6),
('nlp-fundamentals-quiz','What advantage do modern contextual models (like Transformers) have over fixed embeddings for ambiguous words?',ARRAY['No advantage, they perform identically','They generate a different representation for a word depending on its surrounding sentence','Contextual models ignore ambiguous words entirely','They only work on short sentences'],1,'Context-dependent representations resolve ambiguity that fixed embeddings cannot.',7),
('nlp-fundamentals-quiz','What would TF-IDF assign a HIGH weight to?',ARRAY['A word appearing in every document, like "the"','A distinctive word specific to one document''s topic, like a rare medical term','Punctuation marks','The document''s file size'],1,'TF-IDF upweights terms that are distinctive to a specific document relative to the corpus.',8),
('nlp-fundamentals-quiz','What kind of task-relevant information does bag-of-words inherently lose?',ARRAY['Word counts','Meaning conveyed by word order, like "dog bites man" vs "man bites dog"','Vocabulary size','Number of sentences'],1,'Order-dependent meaning is exactly what bag-of-words discards.',9),
('nlp-fundamentals-quiz','Why is extracting named entities from text valuable for a business application?',ARRAY['It has no practical value','It lets structured information, like company names and dates, be pulled automatically from unstructured text','It replaces the need for a database','It only works for legal documents'],1,'NER turns free text into structured, actionable data.',10),

-- ============ computer-vision-quiz ============
('computer-vision-quiz','How is a color image typically represented for a model to process?',ARRAY['As a single number','As a grid of pixels with numeric intensity values per color channel','As a text string','As an audio waveform'],1,'Images are numeric pixel grids across color channels.',1),
('computer-vision-quiz','What does convolution let a CNN do efficiently?',ARRAY['Detect local patterns like edges regardless of position in the image, using shared filters','Compress images for storage','Convert images to text','Only work on grayscale images'],0,'Shared filters detect the same pattern anywhere in the image without a separate weight per position.',2),
('computer-vision-quiz','Which task involves labeling a single category for an entire image?',ARRAY['Object detection','Image classification','Semantic segmentation','All of these equally'],1,'Classification assigns one label to the whole image.',3),
('computer-vision-quiz','Which task gives the precise pixel-level outline of an object, not just a bounding box?',ARRAY['Image classification','Object detection','Semantic segmentation','None of these'],2,'Segmentation labels every pixel, giving a precise outline.',4),
('computer-vision-quiz','Why does data augmentation help prevent overfitting on a small labeled image dataset?',ARRAY['It deletes bad examples','It artificially expands training data with label-preserving transformations like rotation and flipping','It makes training slower','It reduces the number of classes'],1,'Augmentation increases effective training diversity without new labeled data.',5),
('computer-vision-quiz','Why is transfer learning often better than training a vision model from scratch on a small dataset?',ARRAY['Training from scratch is always better','A pretrained model already learned general features like edges and textures that transfer well, even with limited task-specific data','Transfer learning requires no data at all','Pretrained models cannot be fine-tuned'],1,'Pretrained general features give a strong starting point for a small dataset.',6),
('computer-vision-quiz','For a self-driving car needing the precise outline of a pedestrian, which task is most appropriate?',ARRAY['Image classification','Object detection','Semantic segmentation','None are relevant'],2,'Precise outlines require pixel-level segmentation, not a bounding box.',7),
('computer-vision-quiz','Why is a shared convolutional filter more efficient than a separate learned weight per pixel position?',ARRAY['It is not more efficient','It reuses the same small set of weights to detect a pattern anywhere in the image, dramatically reducing parameters','Shared filters only work on black-and-white images','Filters are unrelated to efficiency'],1,'Weight sharing is the core efficiency gain of convolution over fully-connected layers.',8),
('computer-vision-quiz','What is a typical shape representation for a 224x224 color image?',ARRAY['224x224 only','224x224x3','224 only','3x3'],1,'The third dimension represents the three color channels.',9),
('computer-vision-quiz','A labeled dataset has only 2,000 images. What is a standard technique to improve model generalization?',ARRAY['Reduce the dataset further','Data augmentation and/or transfer learning from a pretrained model','Train from scratch with a very large model','Remove all validation data'],1,'Both techniques directly address the small-data problem.',10),

-- ============ generative-ai-quiz ============
('generative-ai-quiz','What makes a model "generative"?',ARRAY['It classifies existing data into categories','It learns the underlying data distribution well enough to produce new, plausible examples','It only works with numbers','It is always larger than a discriminative model'],1,'Generative models produce new examples rather than just labeling existing ones.',1),
('generative-ai-quiz','What is the key difference between generative and discriminative models?',ARRAY['There is no difference','Discriminative models distinguish between categories; generative models produce new data resembling the training distribution','Generative models are always more accurate','Discriminative models cannot be trained on text'],1,'This is the fundamental distinction between the two model families.',2),
('generative-ai-quiz','At a conceptual level, how do diffusion models generate images?',ARRAY['By directly copying training images','By learning to reverse a noise-adding process, starting from random noise and iteratively denoising it','By searching a database of images','By using only text without any image data'],1,'Diffusion models learn to denoise, generating images from pure noise.',3),
('generative-ai-quiz','Why might an image-generation model produce an anatomically implausible number of fingers on a hand?',ARRAY['This never happens','It learned statistical patterns of what hands look like rather than an explicit counting rule','The model is broken and needs to be replaced','Hands are impossible to generate'],1,'The model has no explicit rule enforcing exact anatomical counts.',4),
('generative-ai-quiz','What is one responsible-use consideration when shipping a generative-AI feature?',ARRAY['None, generative AI has no risks','Whether the model''s output reflects and amplifies biases present in its training data','Response time only','The programming language used'],1,'Bias inherited from training data is a real, evaluable risk.',5),
('generative-ai-quiz','Which of these is a discriminative task, not a generative one?',ARRAY['Writing a new paragraph of text','Classifying an email as spam or not spam','Generating an image from a text prompt','Writing new code from a description'],1,'Classification is the classic discriminative task.',6),
('generative-ai-quiz','What is a common failure mode of generative text models regarding facts?',ARRAY['They never make mistakes','Hallucination -- producing fluent but factually incorrect content','They refuse to answer factual questions','They only work with true statements'],1,'Hallucination is a well-documented, expected failure mode.',7),
('generative-ai-quiz','Why should copyright/attribution be considered when using generative AI in a product?',ARRAY['It is never a concern','Training data usage and output similarity to existing works raise real legal and ethical questions','Copyright does not apply to AI-generated content anywhere','This is purely a marketing concern'],1,'These are genuinely contested legal and ethical questions in practice.',8),
('generative-ai-quiz','A hiring-assistant tool is built on a generative model trained on historical hiring data. What risk should be evaluated before shipping?',ARRAY['None, historical data is always neutral','The model may learn and reproduce past discriminatory hiring patterns','Model training time','The programming language used'],1,'Historical data often encodes past biases that a model can reproduce.',9),
('generative-ai-quiz','Why is a generative model''s "learned distribution" the key to it producing new examples?',ARRAY['It is not related','It captures the patterns of the training data closely enough to sample new, similar examples from that same pattern space','Distributions are unrelated to generation','Only discriminative models use distributions'],1,'Sampling from a learned distribution is literally how generation works.',10),

-- ============ cloud-security-quiz ============
('cloud-security-quiz','What does the shared responsibility model describe?',ARRAY['The cloud provider is responsible for everything, including customer configuration','A split where the provider secures the underlying infrastructure and the customer secures their own configuration and usage','Only the customer bears any responsibility','Responsibility is randomly assigned per incident'],1,'This split is the foundation of cloud security thinking.',1),
('cloud-security-quiz','What is one of the most common real-world causes of cloud security incidents?',ARRAY['Sophisticated zero-day exploits','Simple misconfigurations, like a publicly exposed storage bucket','Physical data center break-ins','Provider-side hardware failures'],1,'Misconfiguration, not sophisticated attacks, causes most real incidents.',2),
('cloud-security-quiz','What does a CSPM (cloud security posture management) tool do?',ARRAY['Encrypts all data automatically','Continuously scans a cloud environment for misconfigurations and policy violations','Replaces the need for IAM','Only works during manual audits'],1,'CSPM provides continuous automated scanning, not periodic manual checks.',3),
('cloud-security-quiz','Why are manual, periodic security audits alone insufficient for cloud environments?',ARRAY['Manual audits are always sufficient','Cloud environments change constantly, so continuous automated scanning is needed to catch drift into insecure states','Audits are illegal in the cloud','There is no difference between manual and automated'],1,'Continuous change requires continuous scanning.',4),
('cloud-security-quiz','Why is granting the narrowest IAM permission a workload needs considered a security best practice?',ARRAY['It is not a best practice, broader is always better','It limits the damage possible if that specific credential is ever compromised','Narrow permissions make services run faster','IAM permissions do not affect security'],1,'This is the principle of least privilege applied to cloud IAM.',5),
('cloud-security-quiz','What does encryption at rest protect against?',ARRAY['Data intercepted over the network','Data being readable if the underlying storage or a backup is somehow accessed','Phishing attacks','DDoS attacks'],1,'At-rest encryption protects stored, not in-transit, data.',6),
('cloud-security-quiz','What does encryption in transit protect against?',ARRAY['Physical theft of a hard drive','Data being intercepted and read while moving over the network','Malware installation','Weak passwords'],1,'In-transit encryption (TLS) protects network-moving data.',7),
('cloud-security-quiz','Why is encryption at rest alone not sufficient if data moves between services over an unencrypted connection?',ARRAY['It is fully sufficient on its own','The data is still exposed to interception in transit, even if safe on disk','Encryption at rest also covers network transmission automatically','There is no risk in transit'],1,'The two protections cover different attack surfaces and both are needed.',8),
('cloud-security-quiz','A storage bucket is accidentally left publicly readable. What category of security failure is this?',ARRAY['A sophisticated exploit','A common misconfiguration','Not a security issue since no exploit was used','A hardware failure'],1,'This is the textbook example of the most common cloud security failure.',9),
('cloud-security-quiz','Why is understanding the shared responsibility model important for a cloud security engineer?',ARRAY['It is not important','Misunderstanding what the customer is responsible for versus the provider is a common source of real breaches','Providers are responsible for absolutely everything','Customers are responsible for absolutely everything including physical hardware'],1,'Confusion about this boundary is a recurring, real cause of breaches.',10),

-- ============ identity-access-management-quiz ============
('identity-access-management-quiz','What is the difference between identity, authentication, and authorization?',ARRAY['They are the same concept','Identity is who/what an entity is, authentication proves it, and authorization determines what it can do','Authorization always comes before authentication','Identity only applies to human users'],1,'These are three distinct, sequential concepts.',1),
('identity-access-management-quiz','What does RBAC (role-based access control) assign permissions to?',ARRAY['Individual users directly, only','Roles, which are then assigned to users, making access easier to manage at scale','IP addresses','Random tokens'],1,'RBAC decouples permission definition from individual users.',2),
('identity-access-management-quiz','Why does RBAC scale better than assigning permissions directly to individual users?',ARRAY['It does not scale better','Updating one role''s permissions updates access for everyone with that role, instead of updating each user individually','RBAC is required by law','Direct assignment is always faster'],1,'One role update propagates to every user with that role.',3),
('identity-access-management-quiz','What is a common IAM anti-pattern involving "just in case" access?',ARRAY['Granting exactly the access needed','Granting broad access that outlives the actual need and is rarely revisited','Granting no access at all','Reviewing access regularly'],1,'Unreviewed "just in case" access accumulates unnecessary risk.',4),
('identity-access-management-quiz','Why does MFA meaningfully reduce risk even after a password has already been compromised?',ARRAY['It does not reduce risk at all','An attacker still needs the second factor, which the compromised password alone does not provide','MFA replaces the need for passwords entirely','MFA only protects against physical theft'],1,'The second factor blocks access even with a stolen password.',5),
('identity-access-management-quiz','What is a service account / machine identity?',ARRAY['A human administrator''s personal login','A credential used by an application, script, or service rather than a human','A type of firewall rule','A network protocol'],1,'Service accounts are non-human identities for automated systems.',6),
('identity-access-management-quiz','Why is using a shared human administrator''s credentials for an automated script considered poor practice?',ARRAY['It is actually best practice','It is harder to audit and violates least privilege compared to a dedicated, scoped service account','Scripts cannot use credentials at all','Human credentials are always more secure'],1,'Dedicated service accounts are scoped, auditable, and don''t mix human/machine access.',7),
('identity-access-management-quiz','A contractor needs temporary read access to one project. What is the best IAM approach?',ARRAY['Grant permanent admin access to be safe','Grant exactly the needed read access, scoped and with an expiration','Grant no access and hope for the best','Share a personal account'],1,'Scoped, time-bound access matches the actual need.',8),
('identity-access-management-quiz','What does authorization determine, once identity and authentication are established?',ARRAY['Whether the user''s password is strong enough','What the identified, authenticated entity is allowed to do','The user''s physical location','The encryption algorithm used'],1,'Authorization is the permission-checking step.',9),
('identity-access-management-quiz','Why do machine identities often need extra care compared to human accounts?',ARRAY['They do not need any special care','They are long-lived and rarely reviewed by a human logging in regularly, unlike human accounts','Machine identities expire automatically every day','They cannot be granted any permissions'],1,'Lack of regular human review makes stale over-privileged service accounts a real risk.',10),

-- ============ design-patterns-quiz ============
('design-patterns-quiz','What is a design pattern?',ARRAY['A specific piece of code to copy-paste exactly','A named, reusable solution to a commonly recurring design problem, adapted to your situation','A required programming language feature','A type of database schema'],1,'Patterns are approaches, not literal reusable code.',1),
('design-patterns-quiz','What is a common criticism of the Singleton pattern?',ARRAY['It is always the best solution','It introduces hidden global state, making unit testing harder since tests cannot easily swap in a different instance','It requires too much code','It only works in Python'],1,'Global state is the core testability criticism of Singleton.',2),
('design-patterns-quiz','What problem does the Factory pattern solve?',ARRAY['It sorts data efficiently','It encapsulates object creation logic, decoupling calling code from exactly which concrete class gets created','It replaces the need for classes','It only applies to databases'],1,'Factory hides the decision of which concrete class to instantiate.',3),
('design-patterns-quiz','What does the Observer pattern let one object do?',ARRAY['Delete other objects','Notify a list of dependent objects automatically when its state changes, without knowing their specifics','Encrypt its own data','Prevent other objects from being created'],1,'Observer decouples a subject from the specifics of its observers.',4),
('design-patterns-quiz','What real-world software feature commonly relies on the Observer pattern?',ARRAY['A UI component that re-renders automatically when shared state changes','A function that always returns the same value','A static configuration file','A single hardcoded value'],0,'Reactive UI updates are a classic Observer-pattern use case.',5),
('design-patterns-quiz','What does the Strategy pattern allow you to do?',ARRAY['Hardcode one algorithm permanently','Define interchangeable algorithms and swap which one is used at runtime without changing the calling code','Delete unused code automatically','Encrypt strategy documents'],1,'Strategy makes algorithms swappable without touching the calling code.',6),
('design-patterns-quiz','A shipping-cost calculator needs to support flat-rate, by-weight, and by-distance pricing without changing checkout code. Which pattern fits best?',ARRAY['Singleton','Strategy','Factory','Observer'],1,'This is a textbook Strategy pattern use case.',7),
('design-patterns-quiz','Why is a design pattern described as an "approach" rather than reusable code?',ARRAY['Patterns are literally interchangeable code snippets','The same named pattern gets implemented differently depending on the specific language and situation','Patterns can only be used once','Patterns are language-specific keywords'],1,'Implementation details vary even when the underlying approach is the same.',8),
('design-patterns-quiz','The exact class to instantiate depends on a runtime condition, like which payment method was selected. Which pattern addresses this cleanly?',ARRAY['Singleton','Observer','Factory','Strategy'],2,'Factory is specifically for runtime-dependent object creation.',9),
('design-patterns-quiz','What is one specific way the Singleton pattern can make unit testing harder?',ARRAY['It has no effect on testing','A test cannot easily substitute a mock instance since code reaches directly for the one global instance','Singletons make tests run faster','Singletons are required for all tests to pass'],1,'Hardcoded global access prevents easy dependency substitution in tests.',10),

-- ============ clean-code-quiz ============
('clean-code-quiz','Why is choosing a clear variable/function name considered high-leverage?',ARRAY['Names do not matter, code is read only once','A clear name communicates intent without needing a comment, and code is read far more often than written','Names only matter for compiled languages','Long names are always better'],1,'Reading frequency makes naming a high-leverage investment.',1),
('clean-code-quiz','What does a function name needing "and" to describe it usually signal?',ARRAY['Nothing, this is fine','The function is doing more than one job and should likely be split up','The function is too short','The function needs more comments'],1,'"And" in a description signals mixed responsibilities.',2),
('clean-code-quiz','What is the main risk of a comment explaining WHAT confusing code does, rather than clarifying the code itself?',ARRAY['Comments are always accurate forever','The comment can go stale the moment the code changes, since nothing forces it to stay in sync','Comments make code run slower','There is no risk'],1,'Nothing enforces comment-code consistency automatically.',3),
('clean-code-quiz','When are comments most valuable, according to clean code practice?',ARRAY['Explaining every single line of code','Explaining WHY a non-obvious decision was made, not WHAT the code does','Never, comments should always be avoided','Only in test files'],1,'The "why" is the information code alone cannot convey.',4),
('clean-code-quiz','What is a "code smell"?',ARRAY['A guaranteed bug','A surface-level pattern that does not necessarily mean code is broken but often signals future maintenance problems','A required linting rule','A type of security vulnerability only'],1,'Smells are warning signs, not confirmed defects.',5),
('clean-code-quiz','What future problem does duplicated logic copy-pasted in five places tend to cause?',ARRAY['No problem, duplication is efficient','A bug fix applied to one copy but forgotten in the others, creating inconsistency','Faster performance','Better test coverage automatically'],1,'Duplication creates a maintenance trap for future fixes.',6),
('clean-code-quiz','What does the "boy scout rule" recommend?',ARRAY['Never touch code you did not write','Leave code a little better than you found it, even in small ways, each time you touch it','Rewrite the entire codebase at once','Only clean up code during dedicated sprints'],1,'Small, continuous improvement is the core of the boy scout rule.',7),
('clean-code-quiz','Why are small, incremental improvements often more sustainable than periodic large "cleanup" efforts?',ARRAY['Large cleanups are always prioritized and completed','Incremental improvements compound over many contributors without needing a dedicated project that rarely gets prioritized','Incremental changes are illegal in most codebases','There is no difference'],1,'Dedicated cleanup projects often get deprioritized indefinitely.',8),
('clean-code-quiz','A function named handleData() validates and saves a user profile. What is a better name?',ARRAY['process()','validateAndSaveUserProfile()','doStuff()','a1()'],1,'This name communicates exactly what the function does.',9),
('clean-code-quiz','Why is a function that does one clearly-named thing easier to test than one doing several unrelated things?',ARRAY['It is not easier to test','A focused function has a smaller, more predictable set of behaviors to verify in isolation','Testing does not depend on function design','Larger functions are always easier to test'],1,'Single-responsibility functions have fewer paths and states to cover.',10),

-- ============ requirements-analysis-quiz ============
('requirements-analysis-quiz','What is the difference between a business requirement and a functional requirement?',ARRAY['They are identical','A business requirement describes a high-level goal; a functional requirement describes specifically what the system must do to support it','Functional requirements come before business requirements always','Business requirements are only used for marketing'],1,'Business requirements state the goal; functional requirements state the system behavior addressing it.',1),
('requirements-analysis-quiz','What does a user story typically capture?',ARRAY['Only technical implementation details','A requirement from the user''s perspective: role, goal, and reason','Database schema details','Server configuration'],1,'User stories are framed around the user''s role, goal, and motivation.',2),
('requirements-analysis-quiz','Why are acceptance criteria important for a user story?',ARRAY['They are not important','They make "done" objectively testable instead of a matter of opinion','They replace the need for a user story','They are only used for legal compliance'],1,'Acceptance criteria remove ambiguity about when a story is complete.',3),
('requirements-analysis-quiz','Why should a requirements analyst keep asking "why" when a stakeholder requests a specific feature?',ARRAY['To be difficult','Stakeholders often describe a desired solution rather than the underlying problem, and the real need may be better solved differently','Asking why is rude and should be avoided','There is never a deeper need'],1,'The stated request is often a proposed solution, not the actual need.',4),
('requirements-analysis-quiz','What makes a requirement like "the system should be secure" problematic?',ARRAY['Nothing, this is a perfectly good requirement','It is not specific or testable, so people will disagree on whether it is met','Security requirements are always vague','It is too short'],1,'Untestable requirements cannot be objectively verified.',5),
('requirements-analysis-quiz','What does requirements traceability link together?',ARRAY['Nothing useful','A requirement to the design, code, and test cases that implement and verify it','Only the project budget','Only the delivery timeline'],1,'Traceability connects a requirement to everything built to satisfy it.',6),
('requirements-analysis-quiz','A requirement changes from a 24-hour to a 48-hour cancellation window. Why does traceability help here?',ARRAY['It does not help at all','It lets the team quickly find every piece of code, test, and documentation referencing the old rule','Traceability only applies to hardware projects','This scenario requires no changes'],1,'Traceability makes the impact of a requirement change discoverable.',7),
('requirements-analysis-quiz','A stakeholder asks for "an export-to-Excel button." What is a good follow-up question?',ARRAY['None needed, just build exactly what was asked','What is the underlying need this export would satisfy, such as sharing data with someone who lacks tool access?','Why do you want a button at all?','There is no need to ask questions'],1,'Uncovering the underlying need may reveal a better solution.',8),
('requirements-analysis-quiz','What risk does skipping validation of the underlying business need before writing functional requirements create?',ARRAY['No risk, it is always fine to jump to a solution','Building a well-executed solution to the wrong problem','There is no such thing as a business need','Functional requirements do not need validation'],1,'This is the classic risk of skipping the "why" behind a request.',9),
('requirements-analysis-quiz','Why is "the dashboard should be user-friendly" a weak requirement compared to "a first-time user should complete the primary task within 2 minutes without help"?',ARRAY['They are equally good requirements','The second gives a concrete, testable target while the first offers no way to verify success','The first requirement is more detailed','User-friendliness cannot be defined at all'],1,'Specific, measurable requirements can actually be verified.',10),

-- ============ mobile-development-quiz ============
('mobile-development-quiz','What is a key tradeoff of native mobile development compared to cross-platform frameworks?',ARRAY['Native always requires less code','Native gives full platform-API access and typically best performance, at the cost of maintaining separate codebases per platform','Cross-platform is always higher performance','There is no tradeoff'],1,'Native trades development speed for platform-specific capability.',1),
('mobile-development-quiz','Why should a mobile app be designed "offline-first"?',ARRAY['Offline design is unnecessary for mobile','Mobile users frequently lose connectivity, so the app should function reasonably and sync when connectivity returns','Offline-first apps are always slower','Only desktop apps need offline support'],1,'Mobile connectivity is inherently intermittent.',2),
('mobile-development-quiz','Why cannot a mobile app assume it will keep running indefinitely just because the user has not closed it?',ARRAY['It can safely assume this','The OS can background or terminate the app at any time to free memory or manage resources','Mobile apps never get terminated','Only crashed apps get terminated'],1,'The OS actively manages app lifecycle to conserve resources.',3),
('mobile-development-quiz','Why should a half-finished form save its draft state when the app is backgrounded?',ARRAY['It is unnecessary, drafts are never lost','The OS can terminate a backgrounded app at any time, and this prevents losing the user''s progress','Draft saving slows down the app','Forms do not need saving on mobile'],1,'Backgrounded apps are vulnerable to OS termination.',4),
('mobile-development-quiz','Why is app store review timing important when planning a release?',ARRAY['Review is instant, no planning needed','Review can add days to a timeline and a rejection requires resubmission, so review time should be planned for in advance','App stores never reject submissions','Review only applies to paid apps'],1,'Review latency and rejection risk must be built into release planning.',5),
('mobile-development-quiz','Which mobile-specific performance constraint does not apply the same way to a typical desktop web app?',ARRAY['Battery drain from frequent background work, like GPS polling','Server response time','Database query speed','HTML rendering'],0,'Battery is a uniquely mobile constraint.',6),
('mobile-development-quiz','Why might frequent background GPS polling hurt an app''s adoption?',ARRAY['GPS polling has no user-visible effect','It drains battery noticeably, and users notice and may uninstall apps that do this excessively','GPS polling always improves battery life','Users never notice battery drain'],1,'Battery drain is a common, noticeable cause of uninstalls.',7),
('mobile-development-quiz','A small team building an MVP with limited engineering resources wants to ship on both iOS and Android quickly. Which approach is often chosen?',ARRAY['Fully native development on each platform separately','A cross-platform framework sharing most code across platforms','Web-only with no mobile app','Neither iOS nor Android support is possible'],1,'Cross-platform frameworks let small teams ship to both platforms faster.',8),
('mobile-development-quiz','What should happen, from a user''s perspective, when they submit a form right as they lose network connectivity, in a well-designed offline-first app?',ARRAY['The app should crash','The submission should be queued locally and synced automatically once connectivity returns, rather than silently failing','Nothing, offline submissions are always lost','The user must manually resubmit from scratch every time'],1,'Graceful queuing and sync is the core of offline-first design.',9),
('mobile-development-quiz','Why is limited memory a mobile-specific constraint developers must design around?',ARRAY['Memory is unlimited on mobile devices','The OS can and will kill memory-heavy apps to free resources for other apps','Memory constraints only apply to older devices','This is not a real concern'],1,'Memory pressure management is an active OS behavior on mobile.',10),

-- ============ database-administration-quiz ============
('database-administration-quiz','What does RPO (Recovery Point Objective) define?',ARRAY['How long recovery takes','How much data loss is acceptable, measured as a time window','The database''s total storage capacity','The number of backup copies required'],1,'RPO is the acceptable data-loss window.',1),
('database-administration-quiz','What does RTO (Recovery Time Objective) define?',ARRAY['How much data loss is acceptable','How long recovery is allowed to take','The backup file format','The database engine version'],1,'RTO is the acceptable recovery duration.',2),
('database-administration-quiz','Why might a nightly-only backup strategy be insufficient for some businesses?',ARRAY['Nightly backups are always sufficient','It could mean losing up to 24 hours of data, exceeding an acceptable RPO for some businesses','Nightly backups take too much disk space','There is no downside'],1,'A nightly-only strategy has a poor RPO for data-sensitive businesses.',3),
('database-administration-quiz','What does EXPLAIN (or EXPLAIN ANALYZE) show?',ARRAY['The database''s disk usage only','How the database will actually execute a query, including whether it uses an index or a full scan','The list of all tables in the database','The current number of active connections'],1,'EXPLAIN reveals the actual execution plan.',4),
('database-administration-quiz','What does a "sequential scan" in a query plan typically suggest?',ARRAY['The query is already optimized','An index on the filtered column may be missing, causing a full table scan','The database is corrupted','The query has a syntax error'],1,'A seq scan on a filtered query usually points to a missing index.',5),
('database-administration-quiz','What is the main purpose of a read replica?',ARRAY['To permanently replace the primary database','To offload read traffic and provide a failover target, at the cost of some replication lag','To encrypt data at rest','To automatically fix slow queries'],1,'Read replicas offload reads and provide failover, with a lag tradeoff.',6),
('database-administration-quiz','What is a risk of routing reporting queries to a read replica instead of the primary?',ARRAY['No risk at all','Replication lag means the replica might reflect slightly stale data','Read replicas cannot run SELECT queries','Replicas are always faster than the primary with no tradeoffs'],1,'Replication lag is the tradeoff for offloading reads.',7),
('database-administration-quiz','Why does a connection pool improve performance compared to opening a new connection per request?',ARRAY['It does not improve performance','Opening a new connection is relatively expensive, and pooling reuses a smaller set of connections, reducing overhead and avoiding exhausting connection limits','Connection pools use more memory with no benefit','Pooling is only relevant for NoSQL databases'],1,'Reusing connections avoids the overhead and limits of constant new connections.',8),
('database-administration-quiz','Why can adding a NOT NULL column with a default value to a huge table risk an outage?',ARRAY['It never risks an outage','On some databases it can lock the table for a full rewrite, blocking traffic during peak hours','Adding columns is always instant','This only affects small tables'],1,'Some migrations require a full table rewrite that can lock production traffic.',9),
('database-administration-quiz','What is a safer way to run a risky schema migration on a large, high-traffic table?',ARRAY['Run it directly during peak traffic with no precautions','Break it into smaller, safer multi-step migrations, often during lower-traffic periods','Migrations should never be run on large tables','Always drop and recreate the table'],1,'Incremental, low-traffic-window migrations reduce outage risk.',10),

-- ============ apache-spark-quiz ============
('apache-spark-quiz','Why does Spark exist?',ARRAY['To replace SQL entirely','To process datasets too large to fit in memory or process fast enough on a single machine, by distributing work across a cluster','To make small datasets process instantly','To replace Python'],1,'Spark solves the distributed-scale processing problem.',1),
('apache-spark-quiz','Why is Spark often the wrong tool choice for a dataset that fits comfortably in memory on one machine?',ARRAY['Spark is always the best choice regardless of size','It adds unnecessary distributed-computing overhead and complexity for a problem that does not need it','Spark cannot handle small datasets at all','Small datasets require Spark specifically'],1,'Spark''s complexity is only justified once distribution is actually needed.',2),
('apache-spark-quiz','What is the difference between a transformation and an action in Spark?',ARRAY['They are the same','Transformations describe a new dataset without computing it yet; actions actually trigger computation','Actions are always faster than transformations','Transformations always execute immediately'],1,'This is the core lazy-evaluation distinction in Spark.',3),
('apache-spark-quiz','Why does calling .filter() on a Spark DataFrame not immediately compute anything?',ARRAY['filter() is broken','Spark uses lazy evaluation, building an execution plan that only runs when an action like .count() or .write() is called','filter() only works on small datasets','Spark does not support filtering'],1,'Lazy evaluation defers computation until an action triggers it.',4),
('apache-spark-quiz','What advantage does lazy evaluation give Spark''s query optimizer?',ARRAY['None, it has no benefit','It can potentially combine or reorder chained operations for efficiency before any computation actually happens','Lazy evaluation makes queries run slower','It prevents any optimization at all'],1,'Deferred execution lets the optimizer see the whole plan before running it.',5),
('apache-spark-quiz','Why is a groupBy or join often the most expensive operation in a Spark job?',ARRAY['They are actually the cheapest operations','They can require shuffling, redistributing data across the network between workers, which is costly','groupBy and join do not require any data movement','Spark caches all joins automatically for free'],1,'Shuffles across the network are Spark''s most expensive common operation.',6),
('apache-spark-quiz','What does Spark''s partitioning refer to?',ARRAY['Splitting the codebase into files','How data is split and distributed across the cluster''s workers','A type of encryption','A database backup strategy'],1,'Partitioning determines how work is distributed across the cluster.',7),
('apache-spark-quiz','Why is the DataFrame API generally preferred over the lower-level RDD API in modern Spark code?',ARRAY['RDDs do not exist anymore','DataFrames provide a structured, SQL-like interface that benefits from Spark''s Catalyst query optimizer','DataFrames are always slower','RDDs are easier to use'],1,'Catalyst optimization is a major advantage of the DataFrame API.',8),
('apache-spark-quiz','What happens when an action like .count() is finally called after a chain of transformations?',ARRAY['Nothing happens','Spark executes the full accumulated execution plan built up by the preceding transformations','The transformations are discarded','An error is always thrown'],1,'The action triggers execution of the entire lazily-built plan.',9),
('apache-spark-quiz','A 500GB dataset spread across many files needs processing. Is this a good fit for Spark?',ARRAY['No, Spark is only for datasets under 1GB','Yes, this is exactly the scale problem Spark''s distributed processing is designed to solve','Spark cannot handle data spread across multiple files','This dataset should be processed with a single-machine script instead'],1,'This is precisely the scale Spark is built for.',10)

) AS v(assessment_slug, prompt, opts, correct, expl, ord)
JOIN public.assessments a ON a.slug = v.assessment_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.assessment_questions existing
  WHERE existing.assessment_id = a.id AND existing.sort_order = v.ord
);
