-- CONTENT EXPANSION — Phase E (assessment question depth)
--
-- Audited: 11 of the 13 existing assessments had exactly 5 questions
-- (sql-basics, excel-basics, statistics-basics, power-bi-basics,
-- javascript-basics, html-css-basics, api-design-basics, git-basics,
-- machine-learning-basics, deep-learning-basics, r-language-basics). This
-- adds new questions (sort_order continuing from where each assessment
-- left off) bringing every one of them to 10-12 questions, mixing
-- conceptual, practical, scenario, debugging and code/output-reasoning
-- question types at basic-through-advanced difficulty, per assessment.
-- None of these duplicate the 5 (or 10, for r-language) questions already
-- seeded — checked by hand against 20260822065725, 20260825000100 and
-- 20260901010000.

INSERT INTO public.assessment_questions (assessment_id, prompt, options, correct_index, explanation, sort_order)
SELECT a.id, v.prompt, v.opts, v.correct, v.expl, v.ord
FROM (VALUES

-- ============ sql-basics (5 -> 12) ============
('sql-basics','You need each customer''s total order amount from an orders(customer_id, amount) table. Which query is correct?',ARRAY['SELECT customer_id, SUM(amount) FROM orders;','SELECT customer_id, SUM(amount) FROM orders GROUP BY customer_id;','SELECT customer_id, amount FROM orders GROUP BY customer_id;','SELECT SUM(amount) FROM orders GROUP BY amount;'],1,'You must GROUP BY the non-aggregated column (customer_id) for the aggregate SUM to be computed per customer.',6),
('sql-basics','`SELECT customer_id, amount FROM orders GROUP BY customer_id;` fails in strict SQL mode. Why?',ARRAY['GROUP BY requires an ORDER BY','amount is not aggregated and not in the GROUP BY list','customer_id must be aggregated','SELECT cannot follow GROUP BY'],1,'Every selected column must either be in the GROUP BY clause or wrapped in an aggregate function.',7),
('sql-basics','Compared to an equivalent JOIN, a correlated subquery in a WHERE clause typically:',ARRAY['Always runs faster','Re-executes once per outer row, which can be slower on large tables','Cannot reference the outer query','Is required for filtering'],1,'A correlated subquery runs once per row of the outer query, which often performs worse than an equivalent JOIN on large tables.',8),
('sql-basics','Which is most likely to speed up a query that frequently filters `WHERE customer_id = ?`',ARRAY['Adding an index on customer_id','Adding more columns to SELECT','Removing the WHERE clause','Using SELECT *'],0,'An index on the filtered column lets the database look up matching rows without a full table scan.',9),
('sql-basics','What does `WHERE amount = NULL` return?',ARRAY['Rows where amount is NULL','No rows — NULL comparisons are never true','An error','All rows'],1,'NULL represents unknown, so any direct comparison to NULL evaluates to unknown; use IS NULL instead.',10),
('sql-basics','What is the difference between UNION and UNION ALL?',ARRAY['UNION ALL removes duplicates, UNION keeps them','UNION removes duplicate rows across the combined results, UNION ALL keeps all rows including duplicates','They are identical','UNION ALL only works on numeric columns'],1,'UNION performs a duplicate-elimination pass across the combined results; UNION ALL skips that pass and is faster.',11),
('sql-basics','A LEFT JOIN from orders to customers returns more rows than the customers table has. What most likely explains this?',ARRAY['A customer placed multiple orders, so one customer row matches multiple order rows','The join is broken','LEFT JOIN always duplicates rows','customers has duplicate primary keys'],0,'Joins multiply rows on the many side of a one-to-many relationship — each matching order row produces its own output row.',12),

-- ============ excel-basics (5 -> 12) ============
('excel-basics','Which function sums values that meet multiple conditions across different columns?',ARRAY['SUMIF','SUMIFS','ADDIF','TOTALIF'],1,'SUMIFS supports multiple criteria ranges, while SUMIF supports only a single condition.',6),
('excel-basics','Wrapping a formula in IFERROR(...) is most useful for:',ARRAY['Making the formula run faster','Displaying a fallback value instead of an error like #DIV/0!','Sorting the results','Preventing the formula from being edited'],1,'IFERROR catches an error result and substitutes a specified fallback value instead of showing the error.',7),
('excel-basics','A #REF! error typically means:',ARRAY['The formula has a typo in a function name','A cell the formula referenced was deleted','The workbook is protected','A number is too large to display'],1,'#REF! appears when a formula points to a cell reference that no longer exists, usually after a deleted row, column, or sheet.',8),
('excel-basics','INDEX/MATCH is often preferred over VLOOKUP because it:',ARRAY['Is always faster on small sheets','Can look up a value to the left of the search column, unlike VLOOKUP','Does not require an exact match option','Only works with numbers'],1,'VLOOKUP can only search the first column of its range and return columns to the right; INDEX/MATCH can look in any direction.',9),
('excel-basics','Data Validation with a list source is used to:',ARRAY['Restrict a cell''s input to a predefined set of values','Automatically sort a column','Highlight duplicate values','Protect a sheet from edits'],0,'A list-based data validation rule limits what a user can type into a cell to the values you specify.',10),
('excel-basics','A circular reference warning appears when:',ARRAY['A formula references its own cell, directly or through a chain of other cells','Two sheets have the same name','A PivotTable is refreshed','A chart references a hidden column'],0,'Excel cannot resolve a formula that ultimately depends on its own result, so it warns about the circular reference.',11),
('excel-basics','Conditional formatting is best used to:',ARRAY['Change the stored value in a cell','Visually highlight cells based on a rule, without changing the underlying data','Sort the data automatically','Validate typed input'],1,'Conditional formatting changes appearance based on rules but never modifies the underlying cell value.',12),

-- ============ statistics-basics (5 -> 12) ============
('statistics-basics','A Type I error occurs when you:',ARRAY['Fail to reject a false null hypothesis','Reject a true null hypothesis','Correctly reject a false null hypothesis','Use too small a sample'],1,'A Type I error is a false positive: rejecting a null hypothesis that is actually true.',6),
('statistics-basics','All else equal, increasing sample size tends to:',ARRAY['Increase the margin of error','Decrease the margin of error, giving a more precise estimate','Have no effect on precision','Guarantee statistical significance'],1,'Larger samples reduce sampling variability, which narrows the margin of error around an estimate.',7),
('statistics-basics','A 95% confidence interval for a mean means:',ARRAY['There is a 95% chance the true mean falls in this specific interval','If you repeated the sampling process many times, about 95% of such intervals would contain the true mean','95% of the data falls in this range','The sample mean is correct 95% of the time'],1,'The 95% describes the long-run behavior of the interval-construction method, not the probability for one specific computed interval.',8),
('statistics-basics','In a normal distribution, approximately what percentage of values fall within one standard deviation of the mean?',ARRAY['50%','68%','95%','99.7%'],1,'The 68-95-99.7 rule states about 68% of values fall within one standard deviation of the mean.',9),
('statistics-basics','A p-value of 0.20 most correctly means:',ARRAY['There is a 20% chance the null hypothesis is true','Assuming the null hypothesis is true, there is a 20% chance of seeing a result this extreme or more','The effect explains 20% of the variance','The test failed'],1,'A p-value is the probability of data at least this extreme, calculated under the assumption the null hypothesis is true — it is not the probability the null hypothesis itself is true.',10),
('statistics-basics','The Central Limit Theorem explains why:',ARRAY['All data is normally distributed','The distribution of sample means approaches normal as sample size grows, even if the underlying data is not normal','Small samples are always unreliable','Correlation implies causation'],1,'The CLT is what lets many statistical methods assume normality of sample means even when the original data is skewed.',11),
('statistics-basics','Using the IQR (interquartile range) method, a value is typically flagged as an outlier if it falls:',ARRAY['Exactly at the median','Below Q1 minus 1.5x IQR or above Q3 plus 1.5x IQR','More than one standard deviation from the mean','Outside the min and max of the dataset'],1,'The common IQR rule flags points beyond 1.5 times the interquartile range past the first or third quartile.',12),

-- ============ power-bi-basics (5 -> 12) ============
('power-bi-basics','What is the key difference between a calculated column and a measure?',ARRAY['They are identical in behavior','A calculated column is computed row-by-row and stored; a measure is computed dynamically at query time based on filter context','Measures use more memory than calculated columns','Calculated columns can only use text functions'],1,'Calculated columns are materialized per row when the data loads; measures recalculate on the fly depending on the current filter context.',6),
('power-bi-basics','In a well-designed star schema, the relationship between a fact table and a dimension table is usually:',ARRAY['Many-to-many','One (dimension) to many (fact)','Many (dimension) to one (fact)','No relationship needed'],1,'Each dimension row (e.g. one product) typically relates to many fact rows (e.g. many sales of that product).',7),
('power-bi-basics','A slicer differs from a standard visual-level filter in that it:',ARRAY['Cannot be used with multiple visuals','Is a visible, interactive filter control placed directly on the report canvas','Only works with numeric fields','Requires DAX to configure'],1,'Slicers are report-canvas filter controls that report viewers can interact with directly, unlike filters configured behind the scenes.',8),
('power-bi-basics','A DAX measure referencing itself, directly or through a chain of other measures, causes:',ARRAY['Faster evaluation','A circular dependency error','Automatic optimization','No effect'],1,'DAX cannot resolve a measure whose evaluation ultimately depends on its own result.',9),
('power-bi-basics','A many-to-many relationship between two tables in Power BI is best handled by:',ARRAY['Ignoring it — Power BI resolves it automatically with no configuration','Introducing a bridge table or explicitly setting the relationship''s cross-filter behavior','Always converting it to a calculated column','Deleting one of the tables'],1,'Many-to-many relationships usually need a bridge table or careful cross-filter direction settings to produce correct aggregations.',10),
('power-bi-basics','Incremental refresh in Power BI is primarily used to:',ARRAY['Refresh only new or changed data instead of reloading the entire dataset','Automatically fix broken DAX formulas','Encrypt the dataset','Convert calculated columns into measures'],0,'Incremental refresh partitions data so only new or changed partitions are reloaded, dramatically speeding up refreshes on large datasets.',11),
('power-bi-basics','Setting a relationship to bidirectional filtering can risk:',ARRAY['Slower report load times only','Ambiguous or unexpectedly duplicated filter propagation across the model','Losing the underlying data','Breaking row-level security entirely'],1,'Bidirectional filters can create ambiguous filter paths in more complex models, sometimes double-counting or producing unexpected results.',12),

-- ============ javascript-basics (5 -> 12) ============
('javascript-basics','What does this log? `for (var i = 0; i < 3; i++) { setTimeout(() => console.log(i), 0); }`',ARRAY['0, 1, 2','3, 3, 3','0, 0, 0','undefined three times'],1,'var is function-scoped, so all three callbacks share the same i, which is 3 by the time they run. (Using let instead would print 0, 1, 2.)',6),
('javascript-basics','Given `const { name, age } = user;`, what is this an example of?',ARRAY['Spread syntax','Object destructuring','Array destructuring','Template literals'],1,'This pulls the name and age properties out of user into their own variables — object destructuring.',7),
('javascript-basics','What does `0 == "0"` evaluate to, and why?',ARRAY['false, because types differ','true, because == coerces types before comparing','true, but only in strict mode','It throws an error'],1,'The loose equality operator == performs type coercion, so the string "0" is converted to the number 0 before comparing.',8),
('javascript-basics','What does `[1, 2, 3].map(x => x * 2).filter(x => x > 2)` return?',ARRAY['[2, 4, 6]','[4, 6]','[1, 2, 3]','[2]'],1,'map doubles each value to [2, 4, 6], then filter keeps only values greater than 2, leaving [4, 6].',9),
('javascript-basics','What is the main difference between `null` and `undefined`?',ARRAY['They are exactly the same','undefined means a variable was declared but not assigned a value; null is an explicit "no value" assigned intentionally','null is only used in arrays','undefined is a syntax error'],1,'undefined is JavaScript''s default for an unassigned variable; null is a value a developer assigns deliberately to represent "nothing".',10),
('javascript-basics','What does the spread operator do in `const copy = [...original, 4];`?',ARRAY['Mutates original by adding 4 to it','Creates a new array with all of original''s elements plus 4','Deletes the last element of original','Merges original into a string'],1,'Spread expands original''s elements into the new array literal without mutating the original.',11),
('javascript-basics','In a Promise chain, what happens if a `.then()` callback throws an error?',ARRAY['The error is silently ignored','It is caught by the next `.catch()` in the chain','The program crashes immediately with no way to handle it','The Promise resolves anyway'],1,'A thrown error inside a .then() rejects the resulting Promise, which propagates to the next .catch() handler in the chain.',12),

-- ============ html-css-basics (5 -> 12) ============
('html-css-basics','Setting `box-sizing: border-box` on an element means:',ARRAY['Padding and border are added outside the specified width/height','Padding and border are included within the specified width/height','The element ignores padding entirely','Only margin is affected'],1,'border-box makes width and height include padding and border, so the element''s total rendered size matches what you set.',6),
('html-css-basics','You need a two-dimensional layout with rows and columns, like a photo gallery grid. Which is generally the better tool?',ARRAY['Flexbox','CSS Grid','Floats','Inline-block only'],1,'Grid is designed for two-dimensional layouts; Flexbox is optimized for one-dimensional rows or columns.',7),
('html-css-basics','An element with `position: absolute` and no positioned ancestor will position itself relative to:',ARRAY['Its immediate parent, always','The nearest ancestor with position other than static, or the initial containing block if none exists','The viewport, always, regardless of ancestors','It cannot be positioned without a parent'],1,'Absolute positioning looks up the ancestor chain for the nearest non-static positioned element; if none exists, it falls back to the initial containing block.',8),
('html-css-basics','Two adjacent vertical margins between sibling block elements can collapse into:',ARRAY['The sum of both margins','The larger of the two margins','Always zero','This never happens in CSS'],1,'Adjoining vertical margins between block-level siblings collapse to the larger of the two values, not their sum.',9),
('html-css-basics','A media query like `@media (max-width: 768px) { ... }` applies its styles when:',ARRAY['The viewport width is exactly 768px','The viewport width is 768px or narrower','The viewport width is wider than 768px','Only on print layouts'],1,'max-width: 768px matches any viewport at or below that width, the standard pattern for mobile breakpoints.',10),
('html-css-basics','Using a real `<button>` instead of a `<div onclick="...">` mainly improves:',ARRAY['Page load speed','Keyboard accessibility and screen-reader semantics for free','SEO ranking only','CSS specificity'],1,'A native <button> is keyboard-focusable and announced correctly by screen readers out of the box; a div needs extra ARIA and tabindex work to match that.',11),
('html-css-basics','An element with `position: relative` and no top/left/right/bottom values set will:',ARRAY['Move to the top-left of its container','Render in its normal document position, but become a positioning reference for absolutely positioned children','Disappear from the layout','Always center itself'],1,'Without offsets, position: relative doesn''t move the element — its main effect here is establishing a positioning context for descendants.',12),

-- ============ api-design-basics (5 -> 12) ============
('api-design-basics','What is the key difference between PUT and PATCH?',ARRAY['They are interchangeable','PUT typically replaces the entire resource; PATCH applies a partial update','PATCH is only for creating resources','PUT cannot be idempotent'],1,'PUT conventionally sends the full resource representation to replace it; PATCH sends only the fields that changed.',6),
('api-design-basics','A request includes valid authentication but the user lacks permission for the action. Which status code fits best?',ARRAY['401 Unauthorized','403 Forbidden','400 Bad Request','404 Not Found'],1,'403 means the server understood who you are but you don''t have permission; 401 means authentication itself is missing or invalid.',7),
('api-design-basics','For a large collection endpoint like GET /orders, which is the best practice for returning results?',ARRAY['Always return every row in one response','Support pagination (e.g. limit/offset or cursor-based)','Require the client to filter results client-side after fetching everything','Return results in random order for performance'],1,'Pagination keeps response sizes manageable and predictable as a collection grows, instead of returning unbounded results.',8),
('api-design-basics','Why is PUT expected to be idempotent while POST is not?',ARRAY['PUT replaces a resource at a known URL — repeating it produces the same end state; POST typically creates a new resource each time it''s called','POST is faster than PUT','Idempotency is not a real REST concept','PUT always fails on the second call'],0,'Calling PUT twice with the same payload leaves the resource in the same state; calling POST twice against a creation endpoint typically creates two resources.',9),
('api-design-basics','RESTful resource naming conventions generally favor:',ARRAY['Verbs in the URL, like /getOrders','Plural nouns representing collections, like /orders and /orders/123','Random identifiers with no structure','Query parameters for the resource type'],1,'REST URLs typically model resources as nouns (/orders, /orders/{id}); the HTTP method conveys the action, not the URL.',10),
('api-design-basics','A `429 Too Many Requests` response typically pairs with which response header to tell the client when to retry?',ARRAY['Content-Type','Retry-After','ETag','Access-Control-Allow-Origin'],1,'Retry-After tells the client how long to wait before making another request, standard practice alongside a 429 response.',11),
('api-design-basics','What is the difference between a 404 and a 410 response?',ARRAY['They mean exactly the same thing','404 means the resource was not found (may or may not have existed); 410 means the resource existed but has been permanently removed','410 means the server is down','404 is only used for POST requests'],1,'410 Gone is a more specific signal than 404 — it tells the client the resource used to exist and won''t be coming back, so it shouldn''t retry.',12),

-- ============ git-basics (5 -> 12) ============
('git-basics','`git stash` is most useful when you want to:',ARRAY['Permanently delete uncommitted changes','Temporarily set aside uncommitted changes to switch branches, then reapply them later','Squash multiple commits into one','Create a new remote repository'],1,'Stash saves your uncommitted working-directory changes so you can switch context cleanly, then restore them with git stash pop.',6),
('git-basics','Checking out a specific commit hash instead of a branch name puts you in:',ARRAY['A new branch automatically','A "detached HEAD" state, where new commits aren''t attached to any branch','An error state that blocks further commands','The same state as checking out main'],1,'HEAD normally points to a branch; checking out a raw commit points HEAD directly at that commit, which is the detached HEAD state.',7),
('git-basics','You just committed but want to undo the commit while keeping the changes staged. Which command does this?',ARRAY['git reset --soft HEAD~1','git reset --hard HEAD~1','git revert HEAD','git checkout HEAD~1'],0,'git reset --soft moves the branch pointer back one commit but leaves the changes staged, ready to be re-committed differently.',8),
('git-basics','The purpose of a `.gitignore` file is to:',ARRAY['List files Git should never track (e.g. build output, secrets)','List all files in the repository','Configure remote URLs','Store commit messages'],0,'.gitignore tells Git which files or patterns to exclude from tracking, keeping generated files and secrets out of version control.',9),
('git-basics','A "fast-forward" merge happens when:',ARRAY['There are conflicting changes on both branches','The target branch has no new commits since the feature branch diverged, so Git just moves the pointer forward','You force-push over history','You merge a branch into itself'],1,'If the base branch hasn''t moved, Git can simply advance its pointer to the feature branch''s latest commit without creating a merge commit.',10),
('git-basics','What is the key difference between `git revert` and `git reset` on a shared branch?',ARRAY['They behave identically','revert creates a new commit that undoes changes, safely preserving history on a shared branch; reset rewrites history, which is risky once pushed and shared','reset is always safer than revert','revert deletes the commit entirely'],1,'On a branch others have already pulled, revert is the safe choice because it adds a new undo commit instead of rewriting history other people depend on.',11),
('git-basics','What is the difference between `git fetch` and `git pull`?',ARRAY['They are identical','fetch downloads remote changes without merging them into your working branch; pull fetches and then merges (or rebases) automatically','pull only works on the main branch','fetch deletes local commits'],1,'fetch is the safe, non-destructive step of downloading remote history; pull additionally integrates that history into your current branch.',12),

-- ============ machine-learning-basics (5 -> 12) ============
('machine-learning-basics','In a binary classifier, recall answers which question?',ARRAY['Of everything predicted positive, how many were correct?','Of all actual positives, how many did the model correctly identify?','How fast is the model?','How many features were used?'],1,'Recall = true positives / (true positives + false negatives) — it measures how many of the real positive cases the model actually caught.',6),
('machine-learning-basics','Why is feature scaling (e.g. standardization) often necessary before training models like k-NN or gradient descent-based models?',ARRAY['It is never necessary','Features on very different scales can dominate distance calculations or slow/destabilize gradient descent convergence','It removes the need for a test set','It automatically fixes overfitting'],1,'Distance-based and gradient-based algorithms are sensitive to feature magnitude, so unscaled features with large ranges can unfairly dominate the model.',7),
('machine-learning-basics','A dataset has 950 negative examples and 50 positive examples. A model that always predicts "negative" gets 95% accuracy. This shows:',ARRAY['The model is excellent','Accuracy alone is misleading on imbalanced data — precision, recall or F1 give a truer picture','The dataset is too small to be useful','The model has zero error'],1,'On imbalanced classes, a trivial model can achieve high accuracy while being useless at the actual task of finding positives, which is why other metrics matter.',8),
('machine-learning-basics','What is the main purpose of k-fold cross-validation?',ARRAY['To make training faster','To get a more reliable estimate of model performance by testing on multiple different train/validation splits','To automatically select features','To replace the need for a test set entirely'],1,'Cross-validation averages performance across several splits, reducing the risk that one lucky or unlucky split gives a misleading performance estimate.',9),
('machine-learning-basics','Data leakage occurs when:',ARRAY['The dataset is too large to fit in memory','Information from outside the training set improperly influences training, inflating performance estimates','A model underfits the data','The learning rate is too high'],1,'Leakage happens when the model gets access, directly or indirectly, to information it wouldn''t have at prediction time — producing performance estimates that don''t hold up in production.',10),
('machine-learning-basics','The bias-variance tradeoff describes the tension between:',ARRAY['Training speed and accuracy','A model too simple to capture patterns (high bias) versus a model too sensitive to training data noise (high variance)','The number of features and file size','Supervised and unsupervised learning'],1,'A high-bias model underfits; a high-variance model overfits — good model selection balances the two.',11),
('machine-learning-basics','Which of these is an unsupervised learning task?',ARRAY['Predicting tomorrow''s stock price from historical labeled prices','Grouping customers into segments with no predefined labels','Classifying emails as spam or not spam using labeled examples','Predicting house prices from labeled sales data'],1,'Clustering customers with no predefined labels is unsupervised — the model finds structure without being told the "correct" groups in advance.',12),

-- ============ deep-learning-basics (5 -> 12) ============
('deep-learning-basics','Dropout is a regularization technique that works by:',ARRAY['Removing training data at random','Randomly disabling a fraction of neurons during each training step, preventing over-reliance on specific neurons','Increasing the learning rate over time','Adding more layers automatically'],1,'Dropout forces the network to not depend too heavily on any single neuron, reducing overfitting by encouraging redundant, robust representations.',6),
('deep-learning-basics','During training, the loss oscillates wildly and never settles down. This is a common symptom of:',ARRAY['A learning rate that is too low','A learning rate that is too high','Too much training data','Using a validation set'],1,'A learning rate that''s too high causes the optimizer to overshoot the minimum repeatedly, producing unstable, oscillating loss.',7),
('deep-learning-basics','The vanishing gradient problem refers to:',ARRAY['Gradients becoming so small in early layers of a deep network that those layers barely update during training','The model running out of memory','Gradients being computed incorrectly by the framework','Overfitting on small datasets'],0,'In very deep networks, repeatedly multiplying small gradient values through many layers during backpropagation can shrink them toward zero, stalling learning in early layers.',8),
('deep-learning-basics','For a task involving sequences, like predicting the next word in a sentence, which architecture family is naturally suited compared to a plain CNN?',ARRAY['A recurrent architecture (RNN/LSTM) or a Transformer, which models order and context across a sequence','A convolutional network with no sequence awareness','K-means clustering','Linear regression'],0,'RNNs, LSTMs and Transformers are designed to model dependencies across sequence positions, which is exactly the structure of language and time-series data.',9),
('deep-learning-basics','Training loss stays flat and high from the very first epoch and never improves. Which is the LEAST likely cause?',ARRAY['The learning rate is far too low or far too high','A bug in how labels are being fed to the model','The model architecture is far too small for the task','The test set is too large'],3,'Test set size doesn''t affect training loss at all — a stuck-flat training loss points to the learning rate, a data/label bug, or an under-capacity model instead.',10),
('deep-learning-basics','A very large batch size compared to a very small one generally leads to:',ARRAY['Identical training dynamics in every case','More stable but less "noisy" gradient estimates, which can occasionally converge to sharper minima that generalize slightly worse','Guaranteed faster convergence in every case','No difference in memory usage'],1,'Larger batches average over more examples per update, giving smoother gradient estimates, but the reduced noise can sometimes hurt generalization compared to smaller, noisier batches.',11),
('deep-learning-basics','One "epoch" of training means:',ARRAY['One single weight update','One complete pass through the entire training dataset','Ten thousand training steps','One layer of the network'],1,'An epoch is a full pass over all training examples once; a single weight update after one batch is usually called a "step" or "iteration".',12),

-- ============ r-language-basics (5 -> 10) ============
('r-language-basics','What does dplyr''s `mutate()` do?',ARRAY['Removes rows matching a condition','Adds a new column or changes an existing one, without collapsing rows','Renames columns','Sorts the data frame'],1,'mutate() creates or modifies columns while keeping the same number of rows, unlike summarise() which collapses to one row per group.',6),
('r-language-basics','What does `mean(c(1, 2, NA, 4))` return by default?',ARRAY['2.33','NA','7','A warning only, then the mean of the non-missing values'],1,'By default, mean() propagates NA — any NA in the input makes the result NA unless you pass na.rm = TRUE.',7),
('r-language-basics','What is the purpose of R''s `factor` data type?',ARRAY['To store decimal numbers with extra precision','To represent categorical data with a fixed, known set of possible levels','To store dates','To speed up numeric computation'],1,'Factors represent categorical variables (like "low"/"medium"/"high") and track their possible levels, which matters for modeling and plotting order.',8),
('r-language-basics','What does R do when you add two vectors of different lengths, like `c(1,2,3,4) + c(1,2)`?',ARRAY['Throws an error immediately','Recycles the shorter vector by repeating it to match the longer vector''s length','Pads the shorter vector with NA','Truncates the longer vector'],1,'R''s vector recycling rule repeats the shorter vector as needed (with a warning if lengths aren''t multiples) to match the longer one, then applies the operation element-wise.',9),
('r-language-basics','Compared to a `for` loop, functions in the `apply` family (like `sapply`, `lapply`) are generally preferred in R because they:',ARRAY['Are always faster in every case with no exceptions','Express the "apply this function to each element" intent more concisely and idiomatically, often returning a usefully structured result','Can only operate on data frames','Cannot be used with custom functions'],1,'The apply family expresses vectorized, functional-style iteration idiomatically in R and often returns cleanly structured output without manual bookkeeping.',10)

) AS v(assessment_slug, prompt, opts, correct, expl, ord)
JOIN public.assessments a ON a.slug = v.assessment_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.assessment_questions existing
  WHERE existing.assessment_id = a.id AND existing.sort_order = v.ord
);
