-- CONTENT EXPANSION — Phase E (assessments), new-skills batch 1
--
-- Audited: none of the 29 skills added in 20260906010000 had an assessment
-- yet. This adds 10 assessments (10 questions each, 100 total) for the
-- skills most central to the new careers: Kubernetes, Terraform, Redis,
-- Data Structures & Algorithms, Test Automation, NumPy, Authentication,
-- Application Security, Prompt Engineering, RAG, and Database Design.
-- Mixes conceptual, practical, scenario-based, debugging and code/output
-- question types per the existing question-quality bar. The remaining ~19
-- new skills are left for a follow-up batch.

INSERT INTO public.assessments (slug, title, skill_id, difficulty, description)
SELECT v.slug, v.title, s.id, v.diff::public.difficulty_level, v.descr
FROM (VALUES
  ('kubernetes-fundamentals-quiz','Kubernetes Fundamentals','kubernetes','intermediate','Pods, Deployments, Services, debugging, and resource management.'),
  ('terraform-fundamentals-quiz','Terraform Fundamentals','terraform','intermediate','Providers, state, variables, plan/apply, and modules.'),
  ('redis-fundamentals-quiz','Redis Fundamentals','redis','beginner','Data types, TTL, the cache-aside pattern, and durability tradeoffs.'),
  ('data-structures-algorithms-quiz','Data Structures & Algorithms','data-structures-algorithms','intermediate','Big-O, arrays vs hash maps, two pointers, stacks/queues, and graph traversal.'),
  ('test-automation-quiz','Test Automation','test-automation','intermediate','The test pyramid, reliable UI tests, flaky tests, and CI strategy.'),
  ('numpy-fundamentals-quiz','NumPy Fundamentals','numpy','beginner','Vectorization, shapes, broadcasting, and boolean indexing.'),
  ('authentication-fundamentals-quiz','Authentication Fundamentals','authentication','intermediate','Authentication vs authorization, password hashing, sessions vs tokens.'),
  ('application-security-quiz','Application Security','application-security','intermediate','SQL injection, XSS, CSRF, and least privilege.'),
  ('prompt-engineering-quiz','Prompt Engineering','prompt-engineering','beginner','Specificity, few-shot prompting, structured output, and evaluation.'),
  ('rag-fundamentals-quiz','Retrieval-Augmented Generation','rag','advanced','Chunking, embeddings, grounding, and evaluating retrieval vs generation.'),
  ('database-design-quiz','Database Design','database-design','intermediate','Normalization, keys, indexing tradeoffs, and relationship modeling.')
) AS v(slug, title, skill_slug, diff, descr)
JOIN public.skills s ON s.slug = v.skill_slug
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.assessment_questions (assessment_id, prompt, options, correct_index, explanation, sort_order)
SELECT a.id, v.prompt, v.opts, v.correct, v.expl, v.ord
FROM (VALUES

-- ============ kubernetes-fundamentals-quiz ============
('kubernetes-fundamentals-quiz','What is the smallest deployable unit in Kubernetes?',ARRAY['Container','Pod','Deployment','Node'],1,'A Pod is the smallest deployable unit, wrapping one or more containers that share network and storage.',1),
('kubernetes-fundamentals-quiz','What is the primary purpose of a Kubernetes Service?',ARRAY['To build container images','To provide a stable network endpoint for a set of Pods','To store secrets','To schedule Pods onto nodes'],1,'Services provide a stable virtual IP/DNS name that load-balances traffic across matching Pods, which get new IPs whenever replaced.',2),
('kubernetes-fundamentals-quiz','A Deployment is configured with replicas: 3. One Pod crashes. What happens?',ARRAY['Nothing, an admin must manually recreate it','Kubernetes automatically creates a replacement Pod','The Deployment is deleted','The remaining 2 Pods permanently absorb the traffic'],1,'The control loop continuously reconciles actual state to desired state, replacing failed Pods automatically.',3),
('kubernetes-fundamentals-quiz','Which command shows WHY a Pod is stuck in Pending or CrashLoopBackOff?',ARRAY['kubectl get pods','kubectl describe pod <name>','kubectl delete pod <name>','kubectl create -f pod.yaml'],1,'kubectl describe pod shows events explaining scheduling failures, image pull errors, and other reasons a Pod is not running.',4),
('kubernetes-fundamentals-quiz','Where should a sensitive value like an API key be stored, rather than a ConfigMap?',ARRAY['A Secret','The container image','An environment variable baked into the Dockerfile','A Pod label'],0,'Secrets are the intended store for sensitive configuration values, though base64-encoded rather than fully encrypted by default.',5),
('kubernetes-fundamentals-quiz','What does setting a memory "limit" on a container prevent?',ARRAY['The container from ever starting','The container from consuming more memory than specified and starving other Pods on the node','The Pod from being scheduled at all','The container from writing logs'],1,'A memory limit caps how much memory a container can use, preventing it from starving other workloads on the same node.',6),
('kubernetes-fundamentals-quiz','A Pod shows status ImagePullBackOff. What is the MOST likely cause?',ARRAY['The node is out of disk space','A typo in the image name/tag or missing registry credentials','The Deployment has too many replicas','The Service selector does not match'],1,'ImagePullBackOff almost always means Kubernetes cannot pull the specified image, usually from a naming typo or missing pull credentials.',7),
('kubernetes-fundamentals-quiz','What is the purpose of a Kubernetes namespace?',ARRAY['To speed up container startup','To partition a cluster''s resources so teams can share it without name collisions','To encrypt traffic between Pods','To automatically scale Deployments'],1,'Namespaces provide logical partitioning within a cluster, useful for separating environments or teams.',8),
('kubernetes-fundamentals-quiz','You need traffic sent to whichever Pods currently match a label, even as Pods are replaced. What resource provides this?',ARRAY['A ConfigMap','A Service','A Namespace','A ReplicaSet referenced directly by IP'],1,'A Service selects Pods by label and provides a stable endpoint independent of individual Pod IP churn.',9),
('kubernetes-fundamentals-quiz','A team just adopted Kubernetes and one engineer keeps editing Deployments directly with kubectl edit in production instead of updating YAML in version control. What is the main risk?',ARRAY['kubectl edit is slower than editing YAML','Changes are not tracked or reviewable and can be silently overwritten by the next declarative apply','Kubernetes does not allow kubectl edit in production','There is no risk, this is standard practice'],1,'Manual edits bypass version control and review, and can be silently reverted the next time the tracked configuration is applied.',10),

-- ============ terraform-fundamentals-quiz ============
('terraform-fundamentals-quiz','What does Terraform''s `plan` command do?',ARRAY['Applies changes immediately','Shows what changes would be made without applying them','Deletes all resources','Initializes a new provider'],1,'terraform plan is a dry run showing exactly what would change, without touching real infrastructure.',1),
('terraform-fundamentals-quiz','Why is Terraform state important?',ARRAY['It stores provider credentials','It maps your configuration to real-world resource IDs so Terraform knows what it already manages','It is just a log file with no functional purpose','It replaces the need for version control'],1,'Without state, Terraform cannot know what it already created, and would try to create duplicates.',2),
('terraform-fundamentals-quiz','What happens if two team members run `terraform apply` at the same time without remote state locking?',ARRAY['Terraform automatically merges the changes','State can become corrupted or changes can conflict destructively','Nothing, Terraform queues the second apply automatically','Terraform always blocks the second apply safely by default'],1,'Without locking, concurrent applies can corrupt state or conflict destructively — this is why remote locking backends exist.',3),
('terraform-fundamentals-quiz','What is the purpose of a Terraform variable?',ARRAY['To store the state file','To let a configuration be reused with different values without editing the code itself','To define provider credentials only','To document the code'],1,'Variables let the same configuration be customized per environment or use case without editing the underlying code.',4),
('terraform-fundamentals-quiz','A plan shows a resource will be destroyed and recreated. What does this usually mean?',ARRAY['Terraform found a syntax error','You changed an attribute that cannot be updated in place and requires replacement','The resource will be duplicated','This is always a Terraform bug'],1,'Certain attribute changes are immutable for a given resource type, forcing Terraform to destroy and recreate it.',5),
('terraform-fundamentals-quiz','What is a Terraform module?',ARRAY['A cloud provider''s SDK','A reusable, parameterized package of Terraform configuration','A type of state file','A built-in Terraform command'],1,'A module is the Terraform equivalent of a function — reusable configuration parameterized by inputs.',6),
('terraform-fundamentals-quiz','Why should terraform.tfstate generally NOT be committed to a public git repository?',ARRAY['It is too large','It can contain sensitive data like resource attributes and sometimes secrets','Git does not support state files','It would break terraform plan'],1,'State files can contain sensitive values, so committing them to a public repo risks exposing that data.',7),
('terraform-fundamentals-quiz','A junior engineer manually resizes a VM in the console after it was created by Terraform. What will the next `terraform plan` show?',ARRAY['Nothing, Terraform cannot detect manual changes','A diff showing the VM needs to change back to match the declared configuration','An error that crashes Terraform','The VM will be automatically deleted'],1,'Terraform compares the declared configuration against real state and will surface the drift as a pending change.',8),
('terraform-fundamentals-quiz','What is the main advantage of a declarative approach like Terraform over an imperative script when some resources already exist?',ARRAY['Declarative is always faster to write','The tool can compare desired vs actual state and only create what is missing','Imperative scripts cannot create cloud resources at all','There is no difference'],1,'A declarative tool reconciles actual state toward desired state, avoiding duplicate creation that a naive imperative script might cause.',9),
('terraform-fundamentals-quiz','`terraform apply` fails partway through, creating some but not all resources. What should you do next?',ARRAY['Delete the state file and start over','Run plan/apply again — Terraform will pick up from the current state and only create what is still missing','Manually delete every resource via the console first','Terraform cannot recover from partial failures'],1,'Because Terraform tracks state, it can safely resume from wherever it left off rather than starting over.',10),

-- ============ redis-fundamentals-quiz ============
('redis-fundamentals-quiz','Why is Redis significantly faster than a typical disk-based database for simple lookups?',ARRAY['It uses a more efficient SQL engine','It keeps data in memory (RAM) rather than reading from disk','It compresses all data automatically','It only supports very small datasets'],1,'In-memory access is dramatically faster than disk I/O, which is the core reason Redis is used for caching.',1),
('redis-fundamentals-quiz','What is a consequence of Redis''s in-memory design if persistence is not configured?',ARRAY['Data is automatically backed up to the cloud','Data can be lost entirely if the Redis process restarts or crashes','Data becomes read-only after a restart','There is no consequence'],1,'Without RDB snapshots or an AOF log enabled, an in-memory store loses its data on restart.',2),
('redis-fundamentals-quiz','Which Redis data type would you use to build a leaderboard ordered by score?',ARRAY['String','Sorted set','List','Hash'],1,'A sorted set keeps members ordered by score automatically, which is exactly what a leaderboard needs.',3),
('redis-fundamentals-quiz','What does setting a TTL (time-to-live) on a Redis key do?',ARRAY['Limits how large the value can be','Automatically deletes the key after the specified time','Encrypts the key','Prevents the key from ever being read'],1,'TTL is the mechanism behind using Redis as a self-expiring cache.',4),
('redis-fundamentals-quiz','In the cache-aside pattern, what happens on a cache miss?',ARRAY['The request fails immediately','The application queries the real data source, stores the result in the cache, then returns it','Redis automatically fetches the data from the database itself','The user is shown an error page'],1,'Cache-aside puts the application in charge of populating the cache on a miss, not Redis itself.',5),
('redis-fundamentals-quiz','Why is it generally risky to use Redis as the ONLY store for critical, non-reproducible data?',ARRAY['Redis does not support write operations','Data loss on a crash can be permanent unless persistence is carefully configured','Redis is too slow for critical data','Redis can only store text data'],1,'Redis trades durability for speed, so critical data usually needs a durable primary database as well.',6),
('redis-fundamentals-quiz','Which Redis type is best suited to represent a user session object with multiple fields (userId, role, lastSeen)?',ARRAY['String','Hash','Set','Sorted set'],1,'A hash naturally models an object with several named fields.',7),
('redis-fundamentals-quiz','Your product page checks Redis first, and on a miss queries Postgres, stores the result in Redis, then returns it. What caching pattern is this?',ARRAY['Write-through','Cache-aside','Write-behind','No caching pattern, this is invalid'],1,'This is the textbook cache-aside pattern: check cache, fall back to source on a miss, populate cache.',8),
('redis-fundamentals-quiz','Why might you set a TTL on cached data instead of caching it forever?',ARRAY['TTLs are required by Redis and cannot be disabled','Forever-cached data can go stale and never reflect updates to the underlying source','TTLs make Redis run faster','There is no reason, permanent caching is always better'],1,'A TTL bounds how stale cached data can become, forcing periodic refresh from the source of truth.',9),
('redis-fundamentals-quiz','What is a downside of caching an ever-growing dataset with no expiration policy at all?',ARRAY['Redis will automatically shard the data','Memory usage grows unbounded and can eventually exhaust available RAM','Redis will silently start caching to disk instead','There is no downside'],1,'Without eviction or expiration, an ever-growing cached dataset will eventually exceed available memory.',10),

-- ============ data-structures-algorithms-quiz ============
('data-structures-algorithms-quiz','What does Big-O notation describe?',ARRAY['The exact runtime of an algorithm in seconds','How an algorithm''s runtime or memory usage grows as input size grows','The number of lines of code','The programming language''s speed'],1,'Big-O describes growth rate, not a literal measured runtime.',1),
('data-structures-algorithms-quiz','Which is generally faster for checking "has this value been seen before" as a list grows large?',ARRAY['A plain array requiring a linear scan','A hash set with average O(1) lookup','They are always equally fast','A linked list'],1,'Hash-based lookup avoids the linear scan an array-based check requires.',2),
('data-structures-algorithms-quiz','What does a "sliding window" technique typically help avoid?',ARRAY['Using any loops at all','Redundant re-scanning of the same elements in problems involving contiguous subranges','Recursion','Using arrays'],1,'Sliding window reuses work across overlapping subranges instead of rescanning from scratch each time.',3),
('data-structures-algorithms-quiz','Which real-world structure best models "last in, first out" behavior?',ARRAY['A print queue','A browser''s back button history','A checkout line','A calendar'],1,'The most recently visited page is the first one you return to — classic stack (LIFO) behavior.',4),
('data-structures-algorithms-quiz','Which traversal algorithm guarantees the shortest path in an unweighted graph?',ARRAY['DFS','BFS','Both are equally guaranteed','Neither is guaranteed'],1,'BFS explores level by level, which is what guarantees the shortest path in hop count.',5),
('data-structures-algorithms-quiz','Two pointers starting at each end of a sorted array, moving inward, are a common technique for:',ARRAY['Finding a pair that sums to a target value in O(n)','Sorting the array','Reversing the array','Counting duplicates'],0,'This is the classic two-pointer pattern for the "pair sums to target" problem on sorted input.',6),
('data-structures-algorithms-quiz','Why might an algorithm that works fine in testing with 100 items fail in production with 10 million items?',ARRAY['Production servers are always slower','The algorithm''s growth rate may make it impractically slow at scale even though it worked on small inputs','Testing environments use different programming languages','This scenario is not realistic'],1,'Growth-rate problems (like O(n²)) only become visible once input size is large enough.',7),
('data-structures-algorithms-quiz','A queue is best described as:',ARRAY['Last in, first out','First in, first out','Random access','Always sorted'],1,'FIFO — the first item added is the first one processed.',8),
('data-structures-algorithms-quiz','A nested-loop function finding duplicates runs fast on 50 items but takes minutes on 500,000. What is the likely issue?',ARRAY['The programming language is broken','The nested-loop approach is O(n²) and does not scale; a hash-set-based approach would be O(n)','There is a network issue','The list itself is corrupted'],1,'This is a textbook symptom of an O(n²) algorithm hitting scale.',9),
('data-structures-algorithms-quiz','When would DFS typically be preferred over BFS?',ARRAY['When you specifically need the shortest path in an unweighted graph','When exploring all possible paths deeply, like solving a maze, or detecting cycles','DFS is never preferred over BFS','Only for sorting algorithms'],1,'DFS naturally suits exhaustive path exploration and cycle detection, where BFS''s level-by-level guarantee isn''t the priority.',10),

-- ============ test-automation-quiz ============
('test-automation-quiz','According to the test pyramid, which type of test should make up the largest share of a healthy test suite?',ARRAY['End-to-end UI tests','Unit tests','Manual tests','Load tests'],1,'Unit tests are the fastest and cheapest, so they should form the broad base of the pyramid.',1),
('test-automation-quiz','Why is selecting UI elements by a stable test ID generally preferred over selecting by CSS class?',ARRAY['Test IDs are shorter to type','CSS classes often change with styling/redesigns, breaking tests that depend on them','CSS selectors are not supported by automation tools','There is no difference'],1,'A test ID is decoupled from visual styling, so redesigns do not silently break selectors.',2),
('test-automation-quiz','What is a "flaky" test?',ARRAY['A test that always fails','A test that passes and fails intermittently with no code change','A test that runs very slowly','A test with no assertions'],1,'Flaky tests are the defining symptom of timing issues, shared state, or unreliable external dependencies.',3),
('test-automation-quiz','Why is using a fixed sleep(5000) instead of an explicit wait-for-condition considered bad practice?',ARRAY['It is illegal in most testing frameworks','It can cause both flakiness (if the app is slower than expected) and unnecessary slowness (if faster)','It uses too much memory','Sleep functions do not exist in most languages'],1,'A fixed sleep is a guess; waiting for the actual condition is both faster and more reliable.',4),
('test-automation-quiz','What is a common cause of test flakiness related to test data?',ARRAY['Using too many assertions','Tests sharing state, like a hardcoded test account, that collides when tests run in parallel','Using version control','Writing tests in the wrong programming language'],1,'Shared, un-isolated test data is one of the most common sources of intermittent failures.',5),
('test-automation-quiz','Why might a team run a full E2E regression suite nightly instead of on every pull request?',ARRAY['E2E tests are illegal to run frequently','A slow, potentially flaky E2E suite blocking every single PR merge would bottleneck the team''s velocity','Nightly runs are always more accurate','There is no reason, it should always run on every PR'],1,'Slow suites are often scheduled less frequently to avoid bottlenecking every commit.',6),
('test-automation-quiz','A UI test selects a button using a chain of styling classes. After a design refresh, the test fails even though the button still works for users. What is the likely root cause?',ARRAY['The button was actually removed','The test relied on styling classes that changed, rather than a stable identifier','The testing framework is broken','The application has a genuine bug'],1,'This is exactly the failure mode stable test IDs are meant to prevent.',7),
('test-automation-quiz','What does it mean for automated tests to need "test data management"?',ARRAY['Tests never need real data','Tests need predictable data to assert against, via seeding, a reset test database, or generating unique data per run','Only manual tests need data','Test data is generated randomly and does not matter'],1,'Predictable, isolated test data is a prerequisite for reliable automated assertions.',8),
('test-automation-quiz','What is a reasonable strategy for avoiding collisions when parallel tests each need to sign up a new user?',ARRAY['Hardcode the same email for every test','Generate a unique value, like a random email, per test run','Run tests one at a time forever','Disable parallel test execution permanently as the only fix'],1,'Unique per-run data avoids collisions without sacrificing parallel execution.',9),
('test-automation-quiz','Why does having too many non-actionable alerts or failing tests in CI eventually make a team less safe, not more?',ARRAY['More failures always mean better coverage','Responders start ignoring or silencing notifications, so a genuinely critical failure can get missed in the noise','CI systems cannot technically handle many failures','This never actually happens in practice'],1,'This is alert fatigue applied to CI — noise erodes trust in the signal.',10),

-- ============ numpy-fundamentals-quiz ============
('numpy-fundamentals-quiz','Why are NumPy arrays generally faster than Python lists for numerical operations?',ARRAY['NumPy arrays use less RAM only','NumPy stores data in a fixed-type contiguous block and performs operations in fast compiled code instead of a Python-level loop','Python lists cannot store numbers','NumPy arrays are always smaller'],1,'The contiguous, fixed-type memory layout is what lets NumPy operate in optimized compiled code.',1),
('numpy-fundamentals-quiz','What is "vectorization" in the context of NumPy?',ARRAY['Converting arrays to strings','Expressing an operation as a whole-array computation instead of a manual element-by-element loop','Drawing vector graphics','Compressing arrays for storage'],1,'Vectorized operations apply to an entire array at once via optimized internal code.',2),
('numpy-fundamentals-quiz','Given arr = np.array([1,2,3,4]), what does arr * 2 return?',ARRAY['[1,2,3,4,1,2,3,4]','An error','array([2,4,6,8])','"2222"'],2,'Multiplying a NumPy array by a scalar applies the operation element-wise.',3),
('numpy-fundamentals-quiz','What does .reshape() do to a NumPy array?',ARRAY['Deletes elements','Changes how the same underlying data is viewed into different dimensions, without copying it','Sorts the array','Converts it to a list'],1,'Reshape reinterprets the same data with a different shape, as long as element counts match.',4),
('numpy-fundamentals-quiz','Given a flat array of 12 numbers, which of these is a VALID reshape target?',ARRAY['(5, 3)','(3, 4)','(7, 2)','(13,)'],1,'3 x 4 = 12, matching the original element count; the others do not.',5),
('numpy-fundamentals-quiz','What does "broadcasting" allow NumPy to do?',ARRAY['Send data over a network','Perform operations between arrays of different but compatible shapes without manually copying data to match sizes','Broadcast the same array to multiple files','It only works with 1D arrays'],1,'Broadcasting lets compatible shapes be combined without explicit manual replication.',6),
('numpy-fundamentals-quiz','What does arr[arr > 100] return, given a NumPy array arr?',ARRAY['The count of elements greater than 100','A new array containing only the elements greater than 100','True or False','The index of the first element greater than 100'],1,'Boolean indexing filters and returns the matching elements themselves.',7),
('numpy-fundamentals-quiz','Why would writing a manual Python for loop to square every element of a large NumPy array be considered poor practice?',ARRAY['Python loops are illegal in NumPy code','It defeats the purpose of using NumPy, since vectorized operations are dramatically faster','Loops always produce wrong results','NumPy arrays cannot be looped over at all'],1,'A manual loop forfeits the compiled-code speed advantage vectorization provides.',8),
('numpy-fundamentals-quiz','What is required for two array shapes to be compatible for broadcasting?',ARRAY['They must be identical','Their dimensions must be equal or one of them must be 1, following NumPy''s broadcasting rules','They must both be 1-dimensional','There is no requirement, any shapes work'],1,'NumPy''s broadcasting rule specifically allows dimensions of size 1 to stretch to match.',9),
('numpy-fundamentals-quiz','np.reshape(arr, (4, 4)) raises an error on an array with 12 elements. Why?',ARRAY['NumPy does not support reshape','The target shape (4x4=16) does not match the original element count (12)','Arrays can only be reshaped to 1D','The array must be sorted first'],1,'Reshape requires the total element count to match the target shape exactly.',10),

-- ============ authentication-fundamentals-quiz ============
('authentication-fundamentals-quiz','What is the key difference between authentication and authorization?',ARRAY['They are the same thing','Authentication proves who you are; authorization determines what you are allowed to do','Authorization happens before authentication always','Authentication is only used for APIs'],1,'The two are distinct steps that both need to happen for a sensitive action.',1),
('authentication-fundamentals-quiz','Why should passwords never be stored in plaintext?',ARRAY['Plaintext takes more storage space','A database breach would immediately expose every user''s real password','Plaintext is slower to query','Passwords are not sensitive data'],1,'Plaintext storage means a single breach compromises every account instantly.',2),
('authentication-fundamentals-quiz','What is the purpose of a per-user salt when hashing passwords?',ARRAY['To make the password easier to remember','To prevent attackers from using precomputed hash tables (rainbow tables) across many users at once','To compress the password','Salts are not used in modern authentication'],1,'A unique salt per user defeats precomputed rainbow-table attacks.',3),
('authentication-fundamentals-quiz','What is a key tradeoff of token-based (JWT) authentication compared to server-side sessions?',ARRAY['JWTs cannot be validated without a database','JWTs are harder to revoke immediately before their natural expiry','JWTs are always less secure','There is no tradeoff'],1,'Server-side sessions can be revoked instantly by deleting the record; JWTs need an extra mechanism like a blocklist.',4),
('authentication-fundamentals-quiz','Why pair a short-lived access token with a longer-lived refresh token, instead of one long-lived token?',ARRAY['It is required by law','It limits the damage if the access token is stolen, while avoiding constant re-authentication','Refresh tokens are faster to generate','There is no real benefit'],1,'This limits the exposure window of a stolen token while keeping the user experience smooth.',5),
('authentication-fundamentals-quiz','Why is storing a JWT in localStorage riskier than storing it in an httpOnly cookie?',ARRAY['localStorage has less storage space','localStorage is readable by any JavaScript on the page, including from an XSS attack, whereas httpOnly cookies are not','localStorage does not support strings','There is no difference'],1,'httpOnly cookies are inaccessible to JavaScript, closing off a whole class of token-theft attacks.',6),
('authentication-fundamentals-quiz','Your app correctly identifies a logged-in user but does not check whether they own the resource they are trying to delete. This is a failure of:',ARRAY['Authentication','Authorization','Encryption','Hashing'],1,'Identity was correctly established; the missing permission check is an authorization failure.',7),
('authentication-fundamentals-quiz','Why is rate-limiting login attempts an important authentication safeguard?',ARRAY['It makes the login page load faster','It reduces the effectiveness of brute-force password guessing attacks','It is required for password hashing to work','It has no security benefit'],1,'Rate limiting slows an attacker down enough to make brute-forcing impractical.',8),
('authentication-fundamentals-quiz','What should happen to existing sessions/tokens when a user changes their password?',ARRAY['Nothing, they remain valid until they naturally expire','Existing sessions/tokens should typically be invalidated, since the old credential may have been compromised','The user should be logged out of nothing','The password change should be blocked'],1,'Invalidating existing sessions closes off access an attacker may have had via the old (possibly compromised) credential.',9),
('authentication-fundamentals-quiz','Why is bcrypt (or Argon2/scrypt) preferred over a fast hash like plain SHA-256 for storing passwords?',ARRAY['bcrypt produces shorter hashes','bcrypt is deliberately slow, making brute-force cracking of stolen hashes far more expensive','SHA-256 does not work with passwords','bcrypt is required by all programming languages'],1,'Deliberate slowness is a security feature for password hashing specifically.',10),

-- ============ application-security-quiz ============
('application-security-quiz','What is SQL injection?',ARRAY['A performance optimization technique','An attack where untrusted input is used to inject malicious SQL logic into a query','A type of database backup','A method for indexing tables'],1,'SQL injection exploits unsanitized input concatenated into a query.',1),
('application-security-quiz','How do parameterized queries prevent SQL injection?',ARRAY['They encrypt the entire database','They treat user input strictly as data, never as executable SQL, regardless of its content','They block all user input entirely','They only work with NoSQL databases'],1,'Parameterization removes the possibility of user input being interpreted as SQL syntax.',2),
('application-security-quiz','What does XSS (cross-site scripting) allow an attacker to do?',ARRAY['Access the physical server','Run arbitrary JavaScript in another user''s browser session','Directly modify the database schema','Intercept network hardware'],1,'XSS runs attacker-controlled script in a victim''s browser session.',3),
('application-security-quiz','What is the primary defense against XSS?',ARRAY['Using HTTPS only','Escaping/encoding untrusted output before rendering it as HTML','Using a longer session timeout','Disabling cookies entirely'],1,'Escaping output prevents untrusted text from being interpreted as executable markup.',4),
('application-security-quiz','What does a CSRF token protect against?',ARRAY['SQL injection','An attacker''s page tricking a logged-in user''s browser into making an unwanted authenticated request','Slow page load times','Password guessing'],1,'CSRF tokens defeat forged requests since the attacker''s page cannot know the token.',5),
('application-security-quiz','Why does client-side (JavaScript) validation alone provide zero real security?',ARRAY['Browsers do not support JavaScript validation','Any client-side check can be bypassed by calling the API directly, e.g. with curl','JavaScript is too slow to validate input','Client-side validation is illegal'],1,'Client-side checks never run for a request sent directly to the API.',6),
('application-security-quiz','What does the principle of least privilege recommend?',ARRAY['Giving every service admin access for convenience','Granting every user/service only the minimum permissions actually needed for its job','Granting the same access to all accounts','Disabling all permissions by default with no exceptions ever'],1,'Least privilege limits the blast radius of any single compromised credential.',7),
('application-security-quiz','A query is built by string-concatenating user input directly into SQL. What is the risk?',ARRAY['None, this is standard practice','An attacker can submit input that breaks out of the intended string and injects arbitrary SQL','This will always throw a syntax error','This approach is actually more secure'],1,'This is the exact mechanism behind SQL injection.',8),
('application-security-quiz','Why is it risky to grant a reporting service the same database credential used for schema migrations?',ARRAY['It is not risky at all','If the reporting service is compromised, the attacker also gains migration/write access it never needed','Migration credentials are always read-only','Reporting services do not need any credentials'],1,'Overprivileged credentials expand what a compromised service can do.',9),
('application-security-quiz','What is the safest general rule for handling untrusted user input in a web application?',ARRAY['Trust it if it comes from a logged-in user','Always validate and sanitize/escape it server-side, regardless of any client-side checks','Only validate it if it looks suspicious','Client-side validation alone is sufficient'],1,'Server-side validation is the only validation an attacker cannot bypass.',10),

-- ============ prompt-engineering-quiz ============
('prompt-engineering-quiz','Why does a vague prompt like "summarize this" tend to produce inconsistent results?',ARRAY['The model is broken','Without specific constraints (length, format, audience), the model has no clear target to aim for','Summarization is impossible for LLMs','Vague prompts always fail completely'],1,'Specificity is what makes output checkable and repeatable.',1),
('prompt-engineering-quiz','What is "few-shot prompting"?',ARRAY['Asking the model very few questions total','Showing the model one or more examples of the input/output pattern you want','Using a small model instead of a large one','Limiting the prompt to a few words'],1,'Few-shot prompting demonstrates the desired pattern via examples.',2),
('prompt-engineering-quiz','Why is showing one worked example often more reliable than a long paragraph describing a desired format?',ARRAY['Long paragraphs are against the rules','A concrete example demonstrates the pattern directly rather than relying on the model to correctly interpret a verbal description','Examples are always shorter','Models cannot read paragraphs'],1,'Demonstration is often more reliable than description for format-sensitive tasks.',3),
('prompt-engineering-quiz','What does asking a model to "think step by step" (chain-of-thought prompting) typically improve?',ARRAY['Response speed','Accuracy on multi-step reasoning or math problems, by giving the model room to work through intermediate steps','The model''s creativity only','Nothing measurable'],1,'Chain-of-thought gives the model room to reason through intermediate steps as tokens.',4),
('prompt-engineering-quiz','Why is "I tried it a few times and it looked right" NOT sufficient evidence that a prompt is production-ready?',ARRAY['It actually is sufficient evidence','A prompt can behave inconsistently on inputs outside the small sample tested; a systematic evaluation set is needed','Prompts never fail once deployed','Manual testing is illegal'],1,'A handful of manual tries cannot represent the full range of real-world inputs.',5),
('prompt-engineering-quiz','What is a risk of parsing an LLM''s raw text output directly as JSON without validation?',ARRAY['There is no risk','The model may include conversational filler or malformed JSON around the data, breaking a naive parser','JSON is not supported by LLMs','This is always perfectly safe'],1,'Unvalidated parsing of free-form text output is fragile.',6),
('prompt-engineering-quiz','For a data-extraction task needing extremely consistent, factual output, should temperature be closer to 0 or closer to 1?',ARRAY['Closer to 1, for more variety','Closer to 0, for more deterministic and focused output','Temperature does not affect factual tasks','Always use exactly 0.5'],1,'Lower temperature reduces randomness, which suits deterministic extraction tasks.',7),
('prompt-engineering-quiz','What is one advantage of explicitly requesting a specific output schema, versus just asking for "the data"?',ARRAY['It makes the model faster overall','It significantly reduces unwanted conversational text mixed into the output, making parsing more reliable','Schemas are required by all LLM APIs','There is no advantage'],1,'An explicit schema request narrows the range of plausible output formats.',8),
('prompt-engineering-quiz','Why might chain-of-thought prompting be unnecessary for a simple factual lookup task?',ARRAY['Chain-of-thought always hurts performance','A single-step factual answer does not benefit from intermediate reasoning steps the way a multi-step problem does','Chain-of-thought is banned for factual tasks','It is actually always necessary'],1,'Chain-of-thought''s benefit comes from multi-step reasoning, which a simple lookup does not require.',9),
('prompt-engineering-quiz','What is the main purpose of building an evaluation set of representative inputs before shipping a prompt-based feature?',ARRAY['To make the prompt longer','To systematically catch failures on inputs beyond the few you happened to manually try','Evaluation sets are only for training models','It has no real purpose'],1,'Systematic evaluation catches failure modes ad hoc testing would miss.',10),

-- ============ rag-fundamentals-quiz ============
('rag-fundamentals-quiz','What problem does RAG primarily solve?',ARRAY['Making models faster','Letting a model answer using information it was not trained on, by retrieving relevant text at query time','Reducing the cost of training a model from scratch','Making a model''s output shorter'],1,'RAG grounds answers in retrieved, external information the model never saw during training.',1),
('rag-fundamentals-quiz','Why are documents split into smaller chunks before being indexed for RAG?',ARRAY['To make the documents load faster in a browser','Embedding/retrieving an entire long document as one unit loses precision, since you often want a specific relevant passage','Chunking is required by law','It compresses the documents'],1,'Chunking lets retrieval return the specific relevant passage rather than an entire document.',2),
('rag-fundamentals-quiz','What do embeddings capture that a keyword search does not?',ARRAY['Exact character matches only','Semantic similarity, allowing retrieval based on meaning even without shared exact keywords','File size','Nothing extra'],1,'Embeddings represent meaning, enabling retrieval by semantic similarity.',3),
('rag-fundamentals-quiz','Why should a RAG prompt instruct the model to say "I don''t know" if the answer is not in the retrieved context?',ARRAY['It is not necessary','It reduces the likelihood of the model fabricating an answer when the real information was not retrieved','It makes responses shorter','It has no effect on hallucination'],1,'This instruction discourages the model from filling gaps with fabricated content.',4),
('rag-fundamentals-quiz','A RAG system gives a wrong answer. Checking which chunks were actually retrieved tells you:',ARRAY['Nothing useful','Whether the failure is a retrieval problem or a generation problem','The exact training data of the model','How much the API call cost'],1,'Separating retrieval from generation failure is essential to debugging a RAG system.',5),
('rag-fundamentals-quiz','What is a risk of making chunks too small, e.g. one sentence each?',ARRAY['No risk','Chunks may lose surrounding context needed to correctly answer a question','Small chunks are always better','Small chunks make retrieval slower'],1,'Overly small chunks can strip away context needed for a complete answer.',6),
('rag-fundamentals-quiz','What is a risk of making chunks too large, e.g. one chunk per 20-page document?',ARRAY['No risk','Retrieval becomes less precise since a single retrieved chunk may dilute the actually relevant passage among a lot of irrelevant text','Large chunks are always better','Chunk size never matters'],1,'Overly large chunks reduce retrieval precision.',7),
('rag-fundamentals-quiz','Why is fine-tuning generally a worse fit than RAG for keeping answers current with frequently-changing information?',ARRAY['Fine-tuning is always cheaper','Fine-tuning bakes information into model weights at a point in time and does not easily support continuous updates the way retrieval over a live document store does','Fine-tuning is faster at inference time only','There is no difference'],1,'RAG can reflect updated documents immediately; fine-tuning requires retraining.',8),
('rag-fundamentals-quiz','What are the two independent places a RAG system can fail?',ARRAY['Only generation, never retrieval','Retrieval (wrong chunks found) and generation (model does not use the right chunks correctly)','Only the vector database','Only the embedding model'],1,'Both stages can independently cause a wrong final answer.',9),
('rag-fundamentals-quiz','Why does grounding answers in retrieved context reduce, but not eliminate, hallucination?',ARRAY['RAG completely eliminates hallucination with no exceptions','The model can still misinterpret or ignore the retrieved context, or the retrieval step itself can return irrelevant chunks','RAG has nothing to do with hallucination','Hallucination only happens without RAG'],1,'Grounding helps but does not guarantee correct use of the retrieved information.',10),

-- ============ database-design-quiz ============
('database-design-quiz','What is the primary goal of normalization?',ARRAY['To make queries slower on purpose','To minimize redundancy by storing each fact once, preventing update anomalies','To duplicate data for speed','To remove all foreign keys'],1,'Normalization organizes data to avoid storing the same fact in multiple places.',1),
('database-design-quiz','What problem does storing a customer''s address on every order row create, instead of once in a customers table?',ARRAY['No problem, this is best practice','An address change requires updating every order row, and missing one causes inconsistent data','It makes queries faster','It is required for referential integrity'],1,'This is the classic update anomaly normalization prevents.',2),
('database-design-quiz','What does a foreign key constraint enforce?',ARRAY['That a column is unique','That the referenced row in another table must actually exist','That a column can never be NULL','That a table has an index'],1,'Foreign keys enforce referential integrity between related tables.',3),
('database-design-quiz','What is a legitimate reason to deliberately denormalize data?',ARRAY['There is never a good reason','Read performance matters more than write simplicity for a specific, well-understood access pattern','Denormalization is always required','To avoid using foreign keys entirely'],1,'Denormalization is a deliberate tradeoff, not a default choice.',4),
('database-design-quiz','What is the tradeoff of adding an index to a frequently-queried column?',ARRAY['No tradeoff, indexes are always free','Faster reads on that column, but slower writes and more storage, since the index must also be updated','Indexes only affect read speed','Indexes remove the need for primary keys'],1,'Every index adds write overhead in exchange for faster reads.',5),
('database-design-quiz','How is a many-to-many relationship, like students and courses, typically modeled?',ARRAY['A single foreign key column on one of the tables','A separate join table holding pairs of foreign keys referencing both tables','Storing a comma-separated list of IDs in one column','It cannot be modeled in a relational database'],1,'A join table is the standard relational way to represent many-to-many relationships.',6),
('database-design-quiz','What does a primary key guarantee?',ARRAY['That the table has no NULL values anywhere','That each row can be uniquely identified','That the table is indexed on every column','That the table is normalized'],1,'A primary key provides a unique identifier for every row.',7),
('database-design-quiz','Adding an index on a column that is updated on almost every write, but rarely queried, is likely to:',ARRAY['Improve overall performance with no downside','Add write overhead for little to no read benefit','Have zero effect on the database','Always be required for referential integrity'],1,'Indexes should be added based on actual query patterns, not preemptively.',8),
('database-design-quiz','What structure models a one-to-many relationship, like one customer having many orders?',ARRAY['A join table','A foreign key on the "many" side (orders) referencing the "one" side (customers)','Two separate unrelated tables','A single denormalized table always'],1,'The foreign key lives on the many side, pointing back to the one side.',9),
('database-design-quiz','What concrete bug does referential integrity (foreign keys) catch that application code alone might miss?',ARRAY['Slow queries','Inserting a row that references a parent row that does not actually exist ("orphaned" data)','Typos in column names','Missing indexes'],1,'Foreign key constraints enforce this at the database level regardless of application code correctness.',10)

) AS v(assessment_slug, prompt, opts, correct, expl, ord)
JOIN public.assessments a ON a.slug = v.assessment_slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.assessment_questions existing
  WHERE existing.assessment_id = a.id AND existing.sort_order = v.ord
);
